{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Week4_5조_강은서"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. VGG19- CIFAR10\n",
    "- 코드: https://github.com/deeplearningzerotoall/PyTorch/blob/master/lab-10_5_2_Aadvance-CNN(VGG_cifar10).ipynb\n",
    "- 위의 코드에서 cfg 리스트를 VGG19에 맞게 수정후 epoch=2로 트레이닝, 16개의 convolution layer+ 3개의 fully connected layer\n",
    "- 정확도 보고할 필요 X"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.optim as optim\n",
    "import torchvision\n",
    "import torchvision.transforms as transforms"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "#loss tracker 함수 정의\n",
    "def loss_tracker(loss_plot, loss_value, num):\n",
    "    '''num, loss_value, are Tensor'''\n",
    "    vis.line(X=num,\n",
    "             Y=loss_value,\n",
    "             win = loss_plot,\n",
    "             update='append'\n",
    "             )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "device = 'cuda' if torch.cuda.is_available() else 'cpu'\n",
    "\n",
    "torch.manual_seed(777)\n",
    "if device =='cuda':\n",
    "    torch.cuda.manual_seed_all(777)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to ./cifar10\\cifar-10-python.tar.gz\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "d4f40362bb9e4d53936db1f03b8eacfc",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(FloatProgress(value=1.0, bar_style='info', max=1.0), HTML(value='')))"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Extracting ./cifar10\\cifar-10-python.tar.gz to ./cifar10\n",
      "Files already downloaded and verified\n"
     ]
    }
   ],
   "source": [
    "transform = transforms.Compose(\n",
    "    [transforms.ToTensor(),# 데이터 폼 텐서로 변환\n",
    "     transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])#정규화하기\n",
    "\n",
    "trainset = torchvision.datasets.CIFAR10(root='./cifar10', train=True,\n",
    "                                        download=True, transform=transform)\n",
    "\n",
    "trainloader = torch.utils.data.DataLoader(trainset, batch_size=512, \n",
    "                                          #batch_size 512\n",
    "                                          # testloader에서만 shuffle=True로 바꿔줄것!\n",
    "                                          shuffle=True, num_workers=0) # num_workers: 멀티 프로세스 값, 디폴트는 0(메인프로세스만)\n",
    "\n",
    "testset = torchvision.datasets.CIFAR10(root='./cifar10', train=False,\n",
    "                                       download=True, transform=transform)\n",
    "\n",
    "testloader = torch.utils.data.DataLoader(testset, batch_size=4,\n",
    "                                         shuffle=False, num_workers=0)\n",
    "\n",
    "classes = ('plane', 'car', 'bird', 'cat',\n",
    "           'deer', 'dog', 'frog', 'horse', 'ship', 'truck') #label 값들"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "%matplotlib inline"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAFEAAAD8CAYAAAAPDUgGAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4xLjMsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy+AADFEAAAgAElEQVR4nOyddXhV1/L3P+tIcuLunpAEd3cvFHcpUqy01CgthToV2tJCoUVaoGiLu7s7ARIkhBCIuyfnRI7u948d+uPet5r2trk8d57nPDl7nS2zJ2vWmjXfmVlCkiT+R3+OFP80A08C/U+IfwH9T4h/Af1PiH8B/U+IfwH9T4h/Af3tQhRC9BJCxAshHgghZv/dz/9PkPg77UQhhBK4D/QA0oEoYJQkSXf/Nib+A/R398SWwANJkhIlSTIAm4EBfzMPfzmp/ubn+QFpjx2nA63+/SQhxHPAcwAajXWz0NBAzGYTpaWVlDt5ASABjhWJ2Nr4UFxciFKo0FOMxaCgrMxA7eBgklIzCA8OILuoFFdXNwAsFon7CfehSgM9PT1Qq0wIVOQXlqDTlYk/+lJ/txB/jsH/bzyRJGkFsAIgok64NPeDF6hY8Rnx7afx2gvT+XzxErx9PDh0dTWvjfic2MyVlKZH4OXqh8bGnU9WzaBZrQa89M4KLmx6i/7DRjJmxHB8fP1ITsqgQ+f2LOvfjLuOISjcfWncMJCVC+ZxRyir9VJ/tzqnAwGPHfsDmb92gV5XRJCfN2EfLwNgzMRn8fcLYs7sGbh7K9l+8EcUilwANB4u5BTlc2D5Mb6ZPog+zreJSSsEYO/p49y7uofZcz+hp5cfR5IVdIhLBCAnNZkKJPQVldV6qb97YlEhTyzdgAzkiWW0JEmxv3SNr6+v9Nxzz/0t/K1YsYLMzMw/rM5/a0+UJMkEvAQcAeKArb8mQABzSTlpMdGMeWU6AOs3LKHwwTHOX9hGSbkFpdKeCrMJgKglq/BJzSTZOZV125exdPUithxaC4BbgKBOcATLFqxkW/4SbAPL2HV8CwB2Pi348MMPyc/Pq9Z7/e12oiRJByVJipAkKUySpLm/db5SKCnNKUAtWQBITiqhUbdWRPp5YxSVDOrdGa1W/s3H14tSk+Da5etUanWM6NKCwgeyqg/r0Y8RzzzNe2+/SB0/P3Zm76L/wJ4AFBXl4h3aFoXKulrv9Leqc3Uo1M5dern1SPx7KIitdOXChXXk5FlTVKHj6Z4DsLe1A2HCQeNIsvI2mgZuBNduw/l3vsLd0QEXrwicNMGkisME1lNz57iFTL8MKv2scam0pUPuANZ/9yOeGlvu5iVRWqat2epcHTK4O3FAcYOitm8C0GH8UoJ6fUHDZzbg7iRo1SgEU9UE71+kxLj6Ft+Ofp8uQz6lSZc3CWnyDAAfT9zC5TUKhmkCaKxRMtY5gHZK+bq2YwYQlRmHjbtrtXis8ULUlhTQJtILZco5ABa9OZVQ/WFOLRiKriCfWrnXaW2UZ1l7/1q88PkqBjWqjUdZPMWxJ7FWy/fZu2Iun7w+nU2X4/BWWlFy3RFVhS8At86dJ8AvACsrdbV4rPFCdPUJ4eCZaJRFN+VjN3fOXI5D2DpTq38Z5yqz0Ec6AVCkteLg8QMEB4dy/lwUF6NucOnAZgAkaxtOnzzBjbR0JKUTGem3uXLnEgAdu7QlrEVLbK2qZzbX+DHR3s5a2r73KAXZiSQkpPD2rNkordQIIVAoFIAZUDJnzhz6Dx2KRm2FyWikbmQIl49s4fbdh+SUq+jZ3pkKkwJrWyty9a2ws7Gi0mQm+vROwhyVWDk48eo7H5Odm1fjVyx/mPR6E9+uXk58eSgjG6no3qcffVv3oERvRGvMwVxeyJKVPwLganyIQrLDLJUzY9xEevSfypVLZwlu1JWjyY607DqS8YNbMbLLXfwCrLBX2wGCyLoh2HoEUqqrqBaPNV6drb005CSl8fDo5wBMGjaQL9YtIzcphm+++QZ3vzDeffcdAApLH6AtiqM8P4lFaw8z4933KSmTVyFfvzGN+8eW887QJmQknsPPtS67N20AoAwHFJKEr59ntXis8T1R0lrhHdGUp8ObAFA/MoybhzdiI/QAjB49mvDwcD766COUwpcibQXFhXncnPcmb41oz5R522nU9mme69cch+I7qG1cSUn2Zs3KT2ncrisAV0Q+xsJi9NXsUjV+TPTx9pLWrFzF3XvnKC2zoXM7ay4fukGukxcumkT6dO1G2aUUThS64uLigiRJ6MrL2LxpLf2tK9FaJNz6T6Zux+F4aAQGi+BOuRqFkD062ks/cu3OMSwouXgqhuKC0ifPTiyukLg4/VnibyUD0K/fHOr3bEpR4mXy8lPZuuQY3+8/KJ9sMXD19HYsJjP2NhKKRh3IHdIMgHWr3uP8xf3cuXYHtboSdXkyNqIEAKPFwrTeYUjm6nWoGi9EF42Z87kV7Dl8CoDp47sTezGBILUvDxLyMSgzaderMwAVeiMBPi5UGvR4e3izdss2RFQOABP7P4W1qZLM/CTUGg37d+xC6eACgIeVDycum9BY21SLxxqvzl7h9aRnvtkBgOOVzZyPOoG+xAOFk4ZWA5uhqshnQKfOHNp1Cb/mDXhr+yK8Q/35uuMkbD28sdMo2PnDVq5euICrsy3JmRmE6ItoNnwE+clJqDwjWbHoSxRCQZ6uAr3R9OSZOB6ihPc9z1FYVMJ6wBjcC4ukwmKxsPi1JSxeMANTkuyAuHkrBsfUDBbNXMbSZa/Q4F4BTm6OULc7Qe4KKvXl+LrZ0KZDT4qvnkUKigCg3Cww6PUE+D6hyz4hBB16vYao0rR7m79hYJAzS16fyMdvzSLufiqXSADALywSdy9fJKWgWSMPcu3UWA2MBEBpUaDFBp3eGnXuA9aeusu29fvlZ5hNbFz6MkJUTxw1Xp3/G5yyNV6dsXFg/erlTJm3AX38WUZ0DSOzUEGgu0Tjoe/j7KzC4mjP1Kf7c+NmFNriZPQ6C28v3INSpcRoNHHjxCaahwegcHEnJecB3dr1Y8OGDdSvX5/Y2Fhis7V4WlegcfqbjW0hRACwHvAGLMAKSZK+FkLMAaYAj9zEb0uSdLDqmreAScgL3lckSTryW89xtFHy/szpXI46j6sjFORmkZmvQ1lpy6xxTzNoxET2bfkaA1BQlkny/Wys1WoeJqZQXpaB2koWzPLNu3leGDlkMHJw52maNGnCzp07iYyMxJD/kHXHz2PWl1VLFn9mTDQBr0uSVAdoDbwohKhb9dtCSZIaV30eCbAuMBKoB/QCllWB+b9KeZmZ3Lp8Dt/yqwAkVliTkl9IidKBp8dM59qlE3h4BAEwd/l2JLOCdlPrYpKUWNsFIFRWAJSUlPDG/SS27zlG06ZNqaiooF69egAkJzygS6twfH08qiWIagtRkqQsSZJuVH3XImMmfr9yyQBgsyRJekmSkoAHyGD+r5IQSiodA5m78TwA89/6jANbd/Ht/K/ZcPRTDpy9R5avDoCtCycwblwH/LKdeW1cF14d24Xp4+Sl3ZAhQ1Cq1IRHhFCnmR1+Lg+ZNqw+AFaNp5DuNpjMYku1ZPGXjIlCiGCgCXAFaAe8JIQYB1xD7q1FyAK+/Nhl6fyC0B8H7+3t7Fi/aTtqazsAyq2VvP3xUnycrDl1Zytmbw3RR27TKLQd926Wcf3mXWrXc+apXn1QK1Q0ad8MNaDVahkwYAD5+fn4ubQiQ3uHzQf3AQHU8pMDAlLU1XPK/mkhCiHsgR3AdEmSSoUQ3wIfI4PyHwMLgIn8TuAe/hW89/XxkbTlFZSXy/hx6xZ1ObprNUJtS2gnNzxClNi7eUEiXL6RjEJU0jCsJaOf/wwrGzU2Vjbs3baODRs28N5776HT6TDp48msTCQlRkv9kAAydZWoUWC0/AM9UQihRhbgBkmSdlYJIOex31cC+6sO/zBwD2BQOTDms40IISDnNHPnfY/BYECtVnMr+jiSuwsKSz7XE7Pw8HPAwSOUq1laIlJ+oEJRiLbcjB0heAb64RfgTacOXbm9dR4RPiOIaN2IrLiT9Lc5grOnH3GK0mrJodpjohBCAKuAOEmSvnqs3eex0wYBd6q+7wVGCiGshRAhQDhw9TcZFAJTcQZqQ/lPbVFRUcyePZuishJyow9TGB8jP2DhIj6bNBmf4nRUThWkXDWgUMous0AvL2bN+YSIJg2YsvACWcKGB1FHAWjUYwR1WvTE1sG5WrL4M7NzO2As0FUIEVP1eRr4QghxWwhxC+gCvAZQBdJvBe4Ch4EXJUky/+ZTyouwdQ3GsGcsAGq1mpYtW6JQKCjXGSiJjiLnymkAstPi8A8NJalIT25+Js2D2xFQ2AaA2q378Pyr71NRrGPchH4YtTl0buoPgL3Gmj07tyAU1VPMaquzJEnn+flx7uCvXDMX+E3A/nGySBJOOTd4WFqOF5CXl4ckSbz77rucPrsL9/7jOLNvA0FAi0HPYrRI5KntKCnJ5xZ7ySvUUV/RjaOHt1E7NILGTZtSrNPTp0tzbjzMBmDZyq3Y21ag1Rb9EdZ+ohq/7AtyVErnP2pCpUFiQ3k/UlMzCPb3Y83273jj1edRWUmUlyooKZK4cmEXJUUF3Lqfx+BRPfEJCiH1TiaREfV5fnAvBErUCgtzV37J7fgU7B01NKzbDR93wcmtPxCVZiAxKfXJc8oKlRUbDxZRaGkEQN8+A5g88UWO7onGXu3B+aPJWCyyQgXW74WPTxA7d++iT/cgYnYeYOxQ2aCeO2Ykez94CV1BFmp7H6Kv3ePtMb0AOLLrB8JCAiksqF4sTo3viY2C3KUvn+nJqbM3se4+jLVrvsfb24eY23cYPX4Y1kro2rUDsbcyGD1qCMNG9sEmtB+T6pfj6+OBkPRczXGhjsZEYWkxQYH+6D3dcLNRs2L5Smo17kGrJv4IpYUXX/mEh4l/vCfWeAeExcGdWuNfImJkKWt3XmbnmcsIIVCjYNbU0ThHtMc+si3c2sbD00v5/rVXyShJQPHUatRKgbM18P0c9qVV0L1rF3ZcuE7ygq+otPfFVQU0hpP37xHS/gtKyt+tFo81Xp3NFgsbtx5lx+ELAERdvc2q1atBJXH52i3uXzxJSrps/ixbupbFP6zG2d6KucOakbjxLS4uk0PySorzWPHdKrTFxTg623Fkz3bsA4IBMNg1JvHEmygUv20s/BzVeCHm5+VSUXyDhGuyTdemeR2mTZzArh3beX/+Irw93HhnYCcAJk7ujpOpFJVDKeaSHK5fvsHBU3KoSNw9LQVpyfhGuiAkaxTlJjYt+w6AuxVPkS91ws7GpVo81vgx8b/BKVvje2KlSceq9d8Qk30cAGtTKrPfGMfIfn3o8nR/uvfrS4+B/QFIydRya9N8rE2FDOjWkgptMbF3bwBwYc1CXOJPMG1kH9r2f4XuQ16g/lMzAHj1uQlUpEbh7elWLR5rvBBNFWZ8XP1pYNsAgCz7FrT46AafLfqctJuXibp4laULlwAwpWcD0j3asm3XQSRHR/bs+5HaIcEARPh6cuJKHAVFlWRlZnD/fgLpV3cC4Ohox4CQHCoNf7gTAv8FQvT2dGHhe+MoUdUCoIOnha9aa+nepi0vvfkGn3/wFhTKy/N0gxX52SlYu/ly8PBBJj7VA5W17JR1d9VQaTYzavx4JGMxbu5ehDaU3ZlZWUU0eH4fmup5wmq+iePo4k27AW/Qrr+FOR9+RHxuOSK/EqVC0KqFH59+uZMlS+cAcHDnWjo2DMRgMhHWsi1+L76EpFRxat4yciO7ElLbSKhCgZR8lYfXS6nEFlRQWXiD5PvlFBUXVovHGt8T9XoD73+7jy9WPwbHSGYsFgsBIQ15cO8Oo4ZPAWDoiElYNLWxYCbbK4OzizdycsZUAIySkZdG9kMhSbRr3ZS7ezfQsLHsmfv4g3fYsPVTjCZTtXis8UJUq1U09TXTPESO7DebzUiSwGIx4xPYlM++nMuCb+RkVW1RPhlp18gp0lBuqiDfcBz7sbIXR6VUsXTrPsorTSTGXqHryAGo82W8WokVYdZWWKmtqsVjjRdicX4B3nqYMnAYAPeKTnH+4U5ulJxl4rhpbNt2isWLDgHwxfpvKLEYKFcVkjl1Azu+v0WzgOEAXD5zjDsJt8lMLyA+5yZuVqVsPC2jFQNm7qbOmN2oNI7V4rHG24l1a0VIHfy8GDFyEmdzkklPSWZgv6eYu+ttno54idqOerYfPUudFq35bsVC2rVrTdtO3bBXl+OWeAZHd28ulkWi1YTQdVgXPp4wlqOb1zK+U28CXJxxfboXYSVn2ZcXxpljh8nJSXvy7ESFUsFXG7egFfK7uQZGEJunQGMJp7gomRylI7EP7gFgY2NL7bp1OXlgA53bNCRWHci6k8kAHNvzDTNHDaXCyshX738JTj7suSt7bU5ujaHPmW0YK/+hiUUIkVzlyY4RQlyranMVQhwTQiRU/XWpahdCiG+qsu5vCSGa/tb9rTQ2KO2d6DqoHwAHTu1h/+nlCLWC9VuPMX/JJiptZNxZKNRsWrmRwmIwlFUwdsQQevVoCIAZBTYaDe4uvrz15mAKikqZNm0oAN3ef4+kSdNRaeyrJYO/qid2qQLqm1cdzwZOSJIUDpyoOgbojYythCNDot/+1o3LjWWcuLGPwzfkVIof1h3hi/d/5PnBk7GvP5jw+k0JDZLzUaxsbXH0cuKhvoyAOn1IzLFl7IzlAKTdiiPuagx2Shc0DXvjN0BDsi4dgPTUC/To2QErpbFaL/+fshMHAJ2rvq8DTgOzqtrXS/JAfFkI4SyE8JEkKeuXblScl81nE14mv6yCkS++QUXhfaTyM9hbNaBeiDWVKWmUWmRs7ONFkyixT0eXmM3WPdvQCBv27NkLgFJtxdbjl7BWq4hOTGHJ2xvZlPAG+UegQdvRvP/uh6hV/xDujIwdHxVCSMDyKszY65FgJEnKEkI8ihT6ucx7P+BfhPg4eO/u7kyfcR0pkUE75sx+D2cXG0pL9lMSn45D01bMntiLm9cuYmsqhRQnKnRBPDdpyk/3i46+gb2VhdysFHJyi+hVx5kJQ/qidrGjQeNgdAVXeHlyB2a8fb9aAvgrhNhOkqTMKkEdE0Lc+5Vz/3DmvV+gt7T5xBUadm5EGDB+0pt42AmMBomAWuGYseW5mR/Qt60Hk4YsR1LII9Txu5Gora2QJIkG1hDcqBfLF69EQoFaZcDBpQRnDwcAmrWdwu3b0UiK6oUb/+kxUZKkzKq/ucAu5PianEf4c9Xf3KrT/zCAb7LosRa+SMjIXEerPRj2vkNiRhIH90XRrkUtJj39FABrF3xBG195chBmHQn73sCuau3s7RyAp7M3vm5+lGScpiTLQLirOwAjBnTi6Okz5GX/4qjyq/SnhCiEsBNCODz6DvREBuv3AuOrThsP7Kn6vhcYVzVLtwZKfm08BKjQWshISibSuRsAQ7++zMmHt6hb+DWepdE0rVOLlNtysNPY19/FKagOE4aPIunMfITGlYybuwEICa1DUK0g/P19mTRqMB07tEFhI/e82a/PYdhT3TCYqufZ/lPGthAiFLn3gTw0bJQkaa4Qwg0ZqA8EUoFhkiQVVkVNLEEOrSsHJkiSdO3XnvHf4JT9U2OiJEmJQKOfaS9ArvPw7+0S8OIfeYa7o5Ix3QSl5TnsveRJAUGUlWopyskisegMOzecYvPqlRi1+VyJOkdCfApuzk7MnvsNG9+dxoTF27h6eCO71y4hwMONxg1r0Xb4eNrX9yfz8EU2pekoyzuLlUNtigoLqiWHGr9iySsoJPlcFFd3yGE7veuoqOuppV6Qgs2LthJ76Qr7d8tmzP17KfQNcOaVCaOxKcuiV8M6mFPlOJ16jRowauwYXOwcCVff4fr8lzkYI3vLEzIcGWBTgrODXbV4rPFC9HB3waNBY5r3bgHAnfgH6AyVmPQWjhw/zbTnJzNsmDz8Nvey51hWHlcvHKOiJJMbxeV8++k8AOwE7Fm3HrPKiLruKCJfXMmwqfIawFldxlvHYrC2/ufsxP8o6YUzZy4byI1PQlXfi/vmOHwaBKNPLObonhV0atMAg5sSCiG6yXwMxTpuhDvSPbiC3i/XQq0wculkNKGqDAImPsWsD36kfd9n2bjrGi9M6A5At2e/xiJJfDB9eLV4rPFCNOlLUBbGYjO6D8ZbBXh1DsY5Rw+WCrINatrY+3HpzH6a+Nais8sVlI3r45Yfw6HrEkUPbhEU4IYGRxqMmk1kcDhBLjsppID4+BhiM2Q70dfJQGrKQ4SlesWFarw6W1tbkyc5MqB+YwAqKyUuaMvI9dWwxbs/x4qD8LkumzhzZ7/O9KfbMmnCWEwmMw6BEeiEHHNYK7g+Botgw5Y1JCU+pLS4lJPb5XXBxX0vcmz7AkyVT2gsTq06jaWF645gqjRw8+Qq5rwzAiQLKCXePlaOpaISs5U9dlF78fMPQa/Xo1aryXvjS/Z42/O6ReLemD7kBTzz0z0/HRWEUoDBYOKbhV9w5ur3ZGYXkhCjx2IxP3mxOKVFuSzcspNCXRkDfSAzrxT9lX5kOc+jdUQ3dEU52Hv5cCMKDCYTkhBYLBaKKkNYsWwmNy6fB5OJjG/7I4SE2s2HnnfHUjvYg65t5DReW1sbvH2dSU/I/Q1ufp5qvDqrNNZ83NuPQzMGA6A7Oo3tuyqJefA6jupKPnl6GD5ZVwAw6iuY+cZLWCwWHgTG8mDDt8xfI68FeowYSb+Jk5BMRfTu0JDDazdxdKNcvsBgNNCyUQBqq/+OqnV/mEpKivhi/X4ad5D9t7VGreeFhSd4fuxZiqKj+GbVRyjtZGxEo7Fl0cJlCAT9tQWUdXiKxs3lBMmA2vVw9w9l6uy5HD0XRYeuzTh+WR4TrYUKi4M95uqBfTV/TFQrFdK6JQuwdfMi5u59PGy8uKl2QaFxZc/C0YSF+GBrbU/bZk8x88VJHF6zjK5jJhH1MAO1RoOdRsPBHbtopYhGY+vAs0sv4RbhyaTpi7By9SDj0HpQVNC8kT2Tpy4hOzvnycNY1EpBmdHAmuWLAejYvg0Rt05gMZTRomkAgwfPQlciFxc6H32Fu9pEouPOMW/G8+x+6yNub5cTzscsusi0Fdf4+J3XMaWk0cq+lMbaKAAeat1ZflpNbm5+tXis8ROLvYMT5ZVGho8eT0JaNrN/2M4XL09n3fhRlOsNqDhCaLDs0npzxuts2LAOW1t7Ipt0pExRydXSPHycvBg8eADde3bBykrJU/WDuH1hP638jIAnOTd3kxX3AD9322rxWOPV2cveQXq1V2cCQ+rxwE6DtlJLWlwSSmc7pkycSYFBycPcEioTjnJw/wWGTm3FmVO3SHgYy+6tFxB2TmxZMo/W41/CYNLjYQNTpvQl3Ksu0VHneHbYRJ5u70pFhZapM77lXkL6k6fOCqVgV4pA5Sj3Ek+3IJILTDjaeWJvZ823Cz/k9BYZjOo2phG5qVryc8xMbt2Mi8d3oE+Ta4xdGv0URdMG8E3PzuTczCNIoURI8j1XLN6KsawCLNXrUDW+JwqFQgoKCKdLnVoEtW5BRk4BDg722FmrOHbyJLXDI3F3d8Xe3h5fKyt0+aW4+AWw4ugqRvQZg9EsUVaiRWe6AuXlbF0Tw559B7mflI2fszXHr1+jVX0Lt1ZuZEl0Lmm5f7wuTo0X4n+DU/bP5PZFPpaOFiOEKBVCTBdCzBFCZPxbqtqja96qAu7jhRBP/Z7nKIU1FnMJKIsB8PDxx7duBDZeXjRpXI8fv1+GXVVgYc+M7zm7/UeuXj6LxqchwXWb4VlPDmjKsK7DpUt7SSgxU8fFGteS+7gWXgcgNDCTPZtWUFpQvdn5zySNxz/KrgeaIbv7H0EFf1nmvbWmgnA/D3QFckW5wspKts17j7SkZGxt7Zj8zCDibkUDsEb0ZewbH9KqfR88PFxw8QmlsY2cavbgwGf4eQXQ21vL/eizeHr4cPa6jJF9/tERxgz2R6GsXqTsX2XidAMeSpKUIsQvMvJT5j2QJIR4lHl/6dduLBTWXIk/h5uvB5RDdnYGXZ+ZzPXL5ynOa0hI084ENTQSn5BIvbr1sdHYcv7sCZrrsnlgMZCekUVYeF1MFoh7mMjVmDt8NfMVNDgwfEQQdwsLkayUbNqlQ9j8s2WuRgKbHjt+qSrWZvWjOBx+Gbj//0gI8ZwQ4poQ4lp2Sjp1jbYMrj8QgFa+jtRxtaNPuzbctOtAlk9vsoMGAWDQqIlJuYKnl57ho4bw8YeLWLtGXh+rXDVkVwgmrYnlRmYJmy9e5mFVIvrgFzy4cDeGwOCwar38XxHQZAX0B7ZVNX0LhAGNkSMbFjw69Wcu/8XMe0mSmkuS1NxercRg6825/dsB2LrqGxYuWUKFoYRWpRsJPD4LxdE5AGiszXjuvsCVq3fRV8K0Cb3p1VGu7TGqR3/q+Phw9rOh+Lh5obEU46SQF8sjuzfjWsw8lL+sRb9Kf0VP7A3ceJRxL0lSjiRJZkmSLMBK/q9YRrUy7x0cXWgaEYadj9xpvYJ9cVJmYW/rgKejN8rQhizdfBiAXq06cLdLZ75ZtYumjZsy8/NlRNaT6y5m5Glp5SKY28aGNi1b8sprH6AScgBTp5arGTdiPmmpD6olgD9t4gghNgNHJElaU3X8U4CSEOI1oJUkSSOFEPWAjchC9UWOFgv/rcTxug0aShuOnSItt4AbOzdyJDaAsnITRlSc/3EQJpMBpVCxZMkSvFqnY9Rb0GkriU3shdliwmQyUV+VSbb5AhkVenRppfh69Eajlqg0Kwh3tWLOnDkANG/enGvXrv29KxYhhC3yBjU7H2v+SzPvc7KyWDBzKqVR8pDr4aph+YIuiEotVmor7OxsiY6XZ2dbWxVPh06g3JSKlaEAS+xR3GzkVwywCqGOqz1u7q4Up91j19rV+PrIIXlms5mDBw9SWfkPYCySJJVLkuQmSVLJY21jJUlqIElSQ0mS+j8eJiJJ0tyqcvmRkiQd+j3PqCgvJS32HuUmufDPO7O6EuzihMkACPh8wce0rspHuXwulr3nrpGVr8Te0ZnP3hyFlC0LOM18By+LDfWbaegzcjzfvv0MJXfl2t2rV6/Gy8sLjUZTLRpPVKAAACAASURBVDnU+LWzo709Hv5uxMfKWabPz9hD97HbUFspEULB7BkfIRdFAa3JxNwFn5Cak4XaUMiSDZsx2cvDcNr9SvbH3CEhNhsvT19M9QfT+ZmXAZgyZUpVuenqUY13hdm5eDPy1UVYhIK7Z3fxQudsjGYLLZo+xXdvvkRyZiwhzZoBnqi0PWnRMpTMY/Ecj53J0bu7sFMqOLr+Ovk6d+o0qkNs1D1+DJlJ+4BarFt3gsENnyUlJUUuzFFe/pv8/BzVeCEKIdCjJrdqw5mku8VYLIKckvXoStP56tOXOLBuBTetu6Fx9MJbr6bQvYz9MbM5sSORpl1kM7VV0iXsij1Qh/tTz7oNp5bsZGiECxZgxIgRGAwGfmWh8KtU49VZIUns/f5rRFXczJYDuzA56SkqMBObX0jDYdN5cbeMlcRfOYLZmM/4kYPpW38YTbspuHpKzpP2n9aH+ABv/OrYotOXkJxvJC5Hzipds2YNK1euxFTNjKoa3xON5SV0buCAj48TMSmVzJ82jGJU2GlzqT/pTS5cOUpFnqyGIb2GYGcs4XxKAaBgRMs3ECh4/4O36NViEhVZm3im74ukXD5A81eHYTRZuJ4Or27TYeVoT2Z59dC+Gi9ESVjw8PTBxcUVUnKYv+oAdeuFoMx/SEWelr2bDxIcHka9oAjSz2wnNeE2PfuOki9WO7Jh1VLiH97j3IVzjBz5MiqVioLMGG4+0JKakEZYt5GYHKGVl5azonq1wmq8OpeXFKHVlXDroAxUaaxsiYtPJqRWJHF5Dxk4qgONm8gz8Ohhz1BQWImvkyNCYcWJbSsxVcoutBbNu6O2tuVm9A28PCLwsBKoVbLQ8r9/mc2zR2Oo1FeLx/85ZR+jJ7Z8QVllCTnaJPbvkZOBrt7PZuPes6zffRKTvpiKghSir8sREBt37KXUYiEmKYH+TimU3s5j/nx544eQRp04dugw+fn5tOgxjKZdB9Gy2xAAAjoMxL/dIMzq6qF9NX5MdHVy5dK5h2jsggGY8uxwYm7FsXrVegqLtTSKjOBBlrxgykxJ5nrMbdrY5zD0s3s0rlMHHzfZvZV6/RBbNiynd9+hXI3OJDsjk00bvwcgIz6WnNRMJPMTWtLFbDAztmcbXh4uh4CfOH6WVd+vQaVS4WFvi9mkJzunKj2jRW0u7N+He9OOFFTAkau3yCmUV50Lv15G96f70bR5cz78Yg5vz3uP5Cw53znY349WHdogpH+wHOp/kuwcHRg7/W3MkpmEpUsIU+Zxcs0MVu28xqdfL2RwxwY8uBNPj249Gd4nnEKNB4dTlZyLOsHKb3/g5DHZvhwzeiiVamvatunMld0rSTIdRmkxEOgygaNr3ic5zYyt+gk1tsvLy5n32Vt0aCMHedr6eDDjg+V8/vkCVCoVqcUmOrZtC8Brcw/yvmsG45rbYi2uEHVgGzNmvgpAcNeRZGoCycjMIy7pJGFBGmpr5EShwydieZh6H1vbfyij6j9Nzs6uHDt2ikOH5F0wHsRlYW9vDQpwc3OlUaNatO0iV2h6p54jx+LyWfDpaq7tz6XdqGc5cfwEAB88NwpN+m2uHFnPzevZ5F5Iw1Ikm0arvnyZ1+bMRSiqF/he800cF1epZ4PG+DdvgsrRgSaqFCRbOxyt1NgG1+NB2jVux9/ExvkpUu8/oFKnx9lNQYcOvfhx7WoWLF/L5i0/8MH774JQIBkrOHrwACahQKFQcvX6TaY9G4qTvQetu79CdEzCk2fi6M0mbhVk8MKsmQDYItHAS01yYTaFqQ9JOnqS3IvyRuUN0FJ4/w7HT5wkIyOLFm3as+CTDwGoG2HH3JkTWfzu6xRqKzBU6DBXyMvFjMRc2jSfgmTUVYvH3yXEKtQuVwhx57G2P5xdL4QYX3V+ghBi/M8969+p3GikZYvmuDnLiY93lelcj8ugRGMgJysBh9D61G4tF5Ocf/IkCrWZyROeoaikjImTXiI1Kf2nF12/9Qde/PQbXOyUODo4Ym0lv/6QER+xcXlPzKb/7G5pa5EB98fpD2XXCyFcgQ+QdxZvCXzwGJz6ixQYEMjs9z4gMyUDgPRkKHI0kxlXxBuLj7HncgYKswx9zvzyLQYN64FzDzumTn6eVau+Z/7CbwCIvV9JfIoJlcoKd2d7nByt8faQMwuG9alHuckMCoffKY5/pd9l4kiSdLaqqvvj9Iey66vOPSZJUiGAEOIY8j9mE79CRcUP+e5EB/oE9QBqkdz7KMmAdQNB9koTffoO5MsdV5j2fDuaNZ2M/vx0zp72ZeqZPpQWl3PhzmHat3iKlp28KddZ8AqAcX3f5E5KPH5aHbjW5myM4NqdeJJT/v7cvn/Jrgd+K7u+WuC9wQBB9+0xWuRe4+gp8HBX4KSBh4lJdOo9jCZhciGN3ItLyW7Sns4NdOj0Cvq2b4C2UAtA48audKrbkEib2oQ27c40kchE51QAWjdoxMK3X0CprDl7mf4SSF8t8F4AOoWCuZ+uA8B233sE3V9Ju4odDBs0nOfauPCgQN4CZPqpWizduBejFIa3mxvPjBhOz5ZyNZJLF3I4fes+Kn89i7+bx6ATSTT98SEAdhpvFv94vtplrv7MiiXnEcb8O7Pr0/k/9X/Ufvq3HlJhVLJ0tw5MznQAhnb7GBTy/6Nul51sSFHQtp8c5bDFYRxWTUF15Qg+jcawI+4szQbVJua0hU7dJxAVfYODB7MY8slH+PcwoDJLcH8Hl5PO0allE+zP/f3G9h/Nrj8C9BRCuFRNKD2r2n6VLCYL0YtyUZpkc6S0IotFyyYAoJF0nN77Ppl35LzzCfu8UdmAtbsgo6CQe4fzuXtThg5UCokxQ4czYvhwnDVK3EQZrg6y+trYWnPk7GWsrf6DtcKEEJuQo7cihRDpQohJwOdADyFEAjKA/3nV6QeBROT9VlYC0wCqJpSPgaiqz0ePJplfI8ki8f46Lxq3kcNBHO29sbWpql+j8cIsOaC2kyd5B4WBIRvc0RYryHqYTy0/Z9SFct1Fk95A/INY+kx4FkPyOfYunknMoTUA6MvK8fVyBOU/UL7g76D/OWX/ArIq1dGo6BQ9msk9SiGV89ILUwit5UNpThKWhIv4+Ms9M6M8gNZtulIm+WM2lZGRkEDUOTmP5dStUxw4uI7L13dxJeMqFzOus/vGGQC27/iBsS88R3F5yc8z8RtU44WosrPlZGwBhmi5RMG873eSlZrDkUMX8VcoqLSzwi1N9idO6N+SJk2bMW5AJwIjFaSlPaRhPTljv1GkI4MHtKZfpyasq9+EMfdK2LVAxm3atmxO9I1YMFVPHDVeiBWSgc7DxmPfUk6Q9K7TnR9Wr+TpLh1p98yrRCUnkWErhxTrdMXYCMEnK/ehUjixeM0qsJKzrWZPfZ+M8mKOnHlA9/UHiXu6Ae9+PwuAuFwta9eswMfjCa2zbe2sktr2q0ehuohBgROp65rPudvZKBDsunedsF5lFOXAQNcXCK9dC1uVEb25nKtHj6KrMKJUGPGq1Y60rJukFFcS4u5N19o+OPkFYqPx4MzV26xdsQyVRZBVVESZ/o+XOK7xPVGgYFj9CJYPk80aK6GgXaQ37ev7Yhtu4sPG79Lotgx1xt6IZs/mK+QW3ydHqyM1rQCDRZ5xGwQ48OyAbtSuHYEkVMTeTwSFDExduniC+6kP8Khmne0aDw9YLBb6j3yFVj0HMGXUKzxILmDAuFdQqDWMN9/gPe1HzO02lOMmOHX+GP2GNaVcnUx5WSkBwf4YTfJqZueBi+hNV/DzsMZdpeJSihO3r98mtF4r+nToQmaZHmfX6u3bV+PV+b/BxKnxPdGo09K5S2csSg1njx/mwMbvmDFuBHfup3Cm2AqtWY2/kz0tInzo3nc85SVFVMbHENGymIQzV/FsOoFDZy6hVF+hzGikc3hL+k34DD9XFam58P7779CjZ1Ps7B358cc11eKxxo+JajsHdFod9+NuATBucD8u3LpHWomO/LtRRLbtjrGbXCtxwqin6du7AwYfZ07t2sKRC4U4+8sq2iq8Ox4mP1wc3PjuzJesOrCB6Z/0BMDRUUmL5r1RKZ5QtK+4uJB335vDezNlc+RmXBp2jl7oCvMp0VWQuHk+l2f1BuDAwcPcun2b2rUb0u2pPuy8dIuSmysAuJF/lHr1/Thy/zTd64+kWZ1OvPvaagDMeh1r172B8T/s2f7HqG69erTt3ItH+91uSnVjb4qasylGErKyuHQ7lsRMGaA/POYVJjSqz/bzMbhb6hDeugcX8kbI1y3P5spdA751ehN/+RYnDp8mL1W+rlvf8cx68ysys6pX3bjGj4kFBYWkZd6mQ3t5w66F4wMJtHXnYFQlcSmJTJ3+GRgF/Vv4UZ6eTM/6rWhdcI8h3x8k/mEWSQGBuLqqibt3j5T6rliHeXH80FqKCgv5+OP3AJCEEWcPH0pLsqvFY43vieUVldyPuUdOpuwUd/EIJteoZPLEEVy9uRR/F2t83OWS+kvykzBkJnFq1R5qN22LV7ce7Dgqpw6GBznTo2MPaoWF0KlzB3RlZcx4/S0Apsw8QO1Os1Coqoex1HgTxyO0tvTckk04aFRUnt0Bno7sO7EJQ6YJfa4BBRJluiImvTCVTz79GCEkJEng6uiKi5ctI0ZORmE2k/UggfKyciShoLDJHDKyM9GXVzAyKAb/tjMoKy/j8+ndyUqOffJWLOqCFDKe60n/Yjmm5vatWxxQQ0FKLkoBz4yZgKoqJM50dR0/TO6AWiXw8DHQq103rPThAPQfMgzvkBBsXb0J9lcTUduP2qGyvLSlpWRkpGN+UqPCXNyceenzcdzaKofBlVo94NTDQiYHeWE0W1izZgVqtTy0G/NuM2tnNAqFkpxka7QVRkouyvmZiWnZFOblkZudxVf9YP1Iid4+8hARdX4fpYbKage+/6YQfwG4/1IIca8KnN8lhFwaTggRLISoeCzr/rvHrmlWla72oArc/11qIymUlCoiiXhOjmTo7DmEhL5TqOzQD0mSUCtVIFUFrHsFI6xsEJIC7+AQYu7dI8NP3k28VYuG1IqoQ7NWTQlo+AqT3vmRF1+Xt2Vq3nEQSkmBuZr7O//mmCiE6AjokLHk+lVtPYGTkiSZhBDzACRJmlWFTe9/dN6/3ecq8CrybuMHgW9+T2qanUJIDQXMfP8DbkkQqMlFYMBkVOKjErgoA9ibnoeNqzNKXRTPT5vH66/NJivpDGE+oZhU5fi3eIYyfQXtmkRg72LHDyu28fXy78jOKWDzls3cph5Xtn5EbmIChsrKv35MlCTpLFD4b21HJUl61PcvIyN3v0hVaKCjJEmXqkD99cDA38Ogysqa0c9N4Mcv5LKmX285S2qWEY2Nkey0XA4eO4FnjqyW6qRiNq5czrkrUcyd/QznrsYxckBrAHp2eoqr0beJz0ike5+ubPxxE7t2bpF/q+3K3LnLCQwM/D0s/f88Vuuqf6WJwJbHjkOEENFAKfCuJEnnkEH69MfO+UXgHv61bL6LrQ0twr1oMOclTpfBy8ObYLFI5OVpadptIKFdLUiSxLnYFHQluSz6dh2twpyJvnGXz2b3R22WVX3rhjUE1ovAw8qbHXt206ZxJPn5RTg4+fPaxP44O7tjZ1+9BMk/u137O4AJ2FDVlAUESpJUIIRoBuyuynP+3cA9/GvZ/MDQWtKtgLaYLUDcdQpKVVhZCfzqNyQkUs+0F+bx0RdzIRYmLT/KW17+FJVocXKU4dAyg5lTixdRP8yHQH8vThw7Tm7AWA7rrFA5qmhOFG+8OJmVG7eTk51RLTn8mZIu44G+wDNVKookSfqqGttIknQdeAhEIPe8x1X+d2XdA2hLC2jm48T+fbKH5eb10xTdu8W+detp1mgq+UnpTB4pb+alcfZg/fo1GIWCyVOG8cbLg5n1mrznin9EGKkpifg4emNMvsikroGkXV0JgG8fa94e3xZnn7+xRLQQohdy8FJ/SZLKH2v3eFSmpaoafDiQWAXea4UQratm5XH8H9j/q+Ro58jcL+fRt40cDdulX3+87VRYWwsCgxywddXw9gQ5Q8CMkmFjJ6NSSAwa9gyp6UqC7eRQkfS8Qg6dvoZrRBCDJj1LvkXJS6/JM35BWRGipz/SLyvHr8vjd8zOm5DDP9yBHOTwuLcAa+BRGNVlSZKeF0IMAT5CVnEz8IEkSfuq7tMcOUTPBjgEvCz9juXSf4NTtsYv+4QQEiip36AjQwZ35OulS3B3cqZ+k8a88PkCXFUqjNpijmzfRp0BUzFa9JSZNKjOvULsfS2hfg7kS3WZO/czVCoFRqORRra2VFhZk1daxotvv8mNO6dwcQjm0OGD5GblPZlCrFu7CSW6fCZPmkju9QOonT2JTi3Cw9ePsDBfMjPyqBUUwdVSF14c2IyPXnudaSMbUV6px6i3UKgKY4irDxeMJbz27hwczIKm/k5MG9iXG46+RF24zM6DhwgMdSEnrfjJWzsD3L0XQ0a6bAuGeDiSmJBISnwsfgOfIV9jRd2O7QCouHmd+R8sxcE2CEePcJqH2PHMAHnbrLYfzGLZrl34Bwbg7uzI5Ode4sXF8mRl76lkzMjhGHTVE0eN74l+oZ7S1Df6UCm0WOXUZ9nVMOqEKfhmXAQTX54KEhTk5vLs+MlERtri498Y77qR6CsL+HLCS6jz0ggaMInWQ5/F2yeAEr2eL15tgEJSYuvVmToevqRkX0OXm82Rozcp1RmfvJ5oNJl4qcEEeq+XK4c8r/iID+rFMeGHfOLj47lxNZpKrez3zsvO4MbNK5w/shmDXoc5OwXXlnIYyeHp7/EgrxRXm0oaBzfmi4938dErrwHQsHVTXpn7Kfb21UuQrPlC1Jt4/ug8Vg5uD0Ddzn2p27YjAz1zUJiVDBrcjx69+wIg7LzJSI/F3ieUhJu3OWdQ0XG0jL8sOb2ZssIcdMKJRasPER19mHc/nAzA1aPnWPL6Czi7uFeLxxqvzkII6d3FO8grLcPb8JD02yep8LNG72jLg9yBKNQqavtYEWGK437Tt366rqM56afv2Tc3c/vKVoYOfIpGnQbyzhtT8A12IC7ZQsfmA+jXtg55BTlMnTWPlNSMJ0+dAWKP7OHZnq0AmPV6F3r7+5GVlkqD2jbknF3I0aVy/p5RaULFY45VIYFC7iQm6whKCyRMpjzsne2p13gGLcPlsJGjp2+x48AVbKq5H8t/hRCfH9aPkli5wG6J2g5Hn0gKUwtwuLeZUGcbNmyuCoo3mflUtwdJkhAKiR0LRv9UbLcwKwtP11AO7TtK5x6TyMu5z94jcvZA7851eKpNCErlExpaB/DmezN54bUXAFhx6B6T536NjdIf3/B6xKWmUruunIGqy84gT6ujy+2FGMsy6TL8RSSjHLh57soVBj3/CsOHT+RefCo6XTn9BsmZ93EP0vDwC3hyS7r4h4Qxf81CenTuD0AbVyd8p7RFOAoiffqwYHE/vB3lHJewY7M47WcmsLYDAbYGTsecxavclRzq8dn6URTfsOPwpVO0+HAiHzafxJq7hzGdTKbXxOmUV+gR1t9Ui8ca3xONlZWQcpa5r8q76mZkW+Ngacf9hFxySktYO+8V8vLkzWgy89K4eTmJ3TseYLKYUJtNHD8r10QsnHGV3ftOYeOqwdfbk/SMQkZH9gHgzU/f4+v5n1BS+oSGG+dkZ5JfkE3s3RQAXD08yTdcYFhYWwZ3bsqaNWvw9vYGILvQRGCzTnStH0hRYiz9Rz6Lg4PsZJp0cjn7dm1h0XtLycgvIzUtheXLZIxl4549+DdohsFYPXWu8SaOj5e/NHPqG4ish5T4uZGWexZrFOjK9dT2ssPG3hoblT3Z+nA6Du9MoE8HDBVmQm0vYeXoiKHSlc+/WENGRgYrV6786b77zsfSr3095syZw43F32Fra8tpfSHZuU/g2rmspIi2nbsR0FY2ms+diuPTuZtZ/O1Rrhy/TWrUHSpNsjr/8NErdO7kzGefNKM4P5f5Q/pxfa5cZ3vs2LH06tWLrl27YrFYeH7MEJZvk8vEdJvUEp235cktuGaR4Lud8ajcZUjmwO5DNGlcF7OhhLAAVwIb1aaosCrbKk9Fkz7u6KggsvZohnc3UjtcDkXu2LEjhw8f5uTJk4SE1mHGyF50a9cBABtnb4IdzJgqyn6eid+gGq/O/w1O2eqC93+4NL4QoldV2wMhxOx/f84vkYOzF50HTKfLQNlZgI0rSgdXLNbO3L13nRApA2e1XFvx83nzmDNnDm+//TaF2Q7s/fFbvCuSASiMPk7SzUsoS+MIcs4mK+UON6/LCIXN4HdxHPUBKjff38vWv9DvsRPXIu+Eu/7f2hdKkjT/8YZ/K43vCxwXQkRU/bwUOQcwHYgSQuyVJOnubz28ID+f779bhRkLkT5w8lwUaxe/w8znp6OyNuNVux6ZdzNACQ3q1GbI4KFkJadgKs3CztEFT19XsovAxqzGOTYOrbYWexJScDGryUk1QDPY/eZQbkZFY6WoXmHe3xTiL2Td/xL9Uml8gAdVu/A+Kis9ALnS8a+SyWRCq9NisZjBR0l+2k369hpC954dOHDpPG1i7nLtZiwNWvegMjMHpZ8Hnq62zJj7LcUlWhxdNXDxFk/PeBUrKyX5+SUUHNlAZWEJ7QfL5Sm8/bzwC3iaU3t2/M7X/Ff6MxPLHymN/7uz7uFfM+/V1ir2P7Tl5amyr++Ld1+kXrgDDZ0rmTW0B2WRA2jfVR41jt+9wqad+zl19TIh3ulEhJXRup6chj1v/hp8m/Rk/fotLJq/nSXfHqJNE7ncvrNVMYGulej/5nDjP1oa/w+D948y7zXWEvs/Dqd7qFzK+8iebQT4ebL7yiV0eLNu0QI2Ho0HYNyoZ9n48ds817sHlSYFaTmVXIiRc5g//WoRF45G4xccxrABw2jQZCBTn/8SgPK0e9y/fBPz31lnuxql8atVMh+gVFfBul27yaqU8/fcXb2oNNny/9o77+ioqrWN/860zKT3XiABUklCDRDpCIJS5BJp0i1wpelFryIoelEBpSkiIoaiAipEQGmCEjqE3hNCSEJ672Xq+f44g/p5UWCE6+jiWStrTc6cs8+ed+29373f9mjrdRxPOc7gKa/wxFiJd7vx+mk2HDpMvq0jepMjoYE+tIqUSlMsWzKf996eQXl5HRPGDqUi/yT6Wkn42dV6Mku0mATLTAkWPfXL0vjA40g89yBl3a8XBGERkmJpDqQgjcTmgiA0BfKQlM+IO3mXytTIQLdcLnwjDeayqNewkcuJjRfY+l4fTuW8hMEEY/sPZH96xU/PPTt3ImID1Dc20MyhKa8k+CMk+FBrsGHn8Sy6veSHvcoVRPAM8EXXWIzSwlrbd7LFuVXW/V2VxjdHkE1GKldwBfjKfO9t4R4YSsTUJLwnSJXbDZk7+HdEDf9+3Ich/Z5kSPeeuJmPvKJJJGHkUA4ePoSurIHerf2R6X5uK1s5GjcbOdWFN3jUaxzON6QcF08bT4Id7TBZGClr9ZvtFoHO4vzn+yDr9Dxndu7itddeZ8XoJzl8NRt9oBfBvv7IZKBydiGnqICy8hJ6duvOhYzzXCoxUXbkAMNGjiQyuisO1ftoHqBiV35Ttia+yIgnJpFVZKRnz6FsWrOIzTt3kpt/95RzVi/EQF+NOPvpMFQ2dmTqehHfJpSraddQGE3MWvQufv6RlBfkMv6Zpxn/1DjcXJ0xGEWmzXkNhVoFiPgrHRj5kAyZIE28xVsvIRdq0VWr8ApqSWFVLuEPufH21ESK8u4+AsLqz84ePhGITafRapDEzRfTpicNJleqcWPGhP6s+88k4l2k3/311t1UlDWSmVWCwimLjOQzxARJ2jmrQkGJ1p3T1wsJHjGf4BEfEvb0RwDMfOV12jcbh5eHj0V9tHoh6vQGMjNzmf/OXADWfPYFq1ctwSDC2S17GTP2KfJdJf3Y65GBzFvxCUsO5NHULQhPP3dCfLsAkPjxWrZt2cLi5V9jEE0cWPs+7z0nuRyCfZpz4tABKossYxq3eiGmpl4hafNGkpMlFgy9wcSIMRPBaMClXRCDHx9MnG8wAOOnTcWrSSgB8nzahfQlNMiRBq00SvPqFbi42BEW6Easwsg/Rk9m1Yq3AdixZzu7krajsrcsPtHqfSwx0dHE9XucymrJ2xfQ/wUABAGY9xn2Yh4GYzUAcZp6mpSk0zwykk9XLUenbeT6lbdp1rYHyxO3IIoifUxGtlyqRvndKg53HIwHkLJ9Dx0dPSgy+2ruFlY/EvPK8ziRcpCWcd0AMGqNiA0GqgoqGDn9FdIKSjl1VdrH+PhmIDTZxq6Dq6mrreGbH09xJk3K13NydqHHQ90YMzABudGARl1C1a7vANCqFXSwt6O+usaiPlq9dnb1dxVd7H2IGNCCNrYxFKcfoEJmRN0oJ9K5jp79R+Lt78XH265QllGIjbKOTt0GsGXTCkpLK9Ab9MT3+weetloup+fTtWtP8pyjaTy6hX7P/oukxIVENglk6bKVpGZnUFryN4xP/FsYZf9saOvqeHzgINqGS6m6acf3IuSkUJR6nO+3f0N1wQ3O14QD0LapLdXXDtB4ZSd9B44iqo07PQY8CUCxuB2F7BD5sh+Z/Ppsuk6fwdiXXwPgqdGDmBx1Ehc3V4v6aPVCVKqUaGuruHr1CgCvv7sYT083HFzdoMFIuJeKHp2lhJ9vVi4jPa+EgtxMhr/4BIKpgU82jgbAsVZFLb0IsvegU1gkM3rHMuRh6bkz68bzzreN6PV6i/po9UIUBLiens7FFClv+avEj/GK6sjEydOQqxVsT0kneaU03V1DPPH3scfbz4O+A6ZwJr+SUqduAJTkuRIX7MX+TSfISk/jyokMzh2ROO8b/HsQ1u2Jv28YSV1tLfMXvEV+RQ2T2sSx5NMt2Kz5Dq0o8OKSzcgUCoyigO7adn64XIednZKauNA44gAAFHxJREFUWhOBDZtRNG+B8Vo9tPZi7/7DnD2fypWsYl567Z+kX0iluFhK/imWqUh4pAfLFi+zqI9WPxKNokh8m7bEBkoWl5179xIQ0hy1SsBkqOf88V2UrpgDgJunO6XFNcTHNcfewY5AXy/aRUvREZ0imuPn4UGfTp14oqkt7ko1C5+VCjaPHvwcyTsOkZpxR4al/4LVC9HLzYneXcNJMMcnzp09C18fJ6Kjoygqrke9ZinO1yRXzeih7ZkxeTjtw8IIDfRhxUfLuHRGOum4egXSrm0nNu3ew5qrcmyCW7DxkrQzSRjxCDXKQotD66x+i+MdFC1OfCsZtVJG45UlPPfUcEqLUklc9Rbzlh8DQUQmynjjjTcICQrC380FfdUlQobNxKDX0yga+ebd+Sz8+HOMOh1yWT3vrduAXCYDsYHcYydpIU/HRqXgn+98SVHlfUjV/fNhwk/MxkmqlcGiT5ZQ3miH3l3iZ/Hx7MBTL84E4Pv9J9m89zC1l9JxL9hC5qUUnATJ2t23Ywdcm9oS1Nyd/V+/R9bpXeza+CkAVaWlGE2g0dwnZiBBEBKREiGLf5E0/iUQar7FGagURTHW7Fq9AqSZvzsmiuJE8zNt+DktbQcw7U7S0uQCVMgc8M5cD4Cj2ofzOaXs3L6Dk8mpqN1tcZOpAZFnhg7hasZlnPy7cWpfMu9/vJ15r0r7xKj20biHeGCjtqXIqORCSQ02zlJ+c51nMHbuAQiy724rsFvBIue9KIpDb34WBGEh8MvAvgxRFGNv0c5HSDnMNzPvH0HK8fv9DioUeLs7Yec9HA4u5YOVK6gqryWse09M9tX4+Bk5WJRMn6Zd6dy3O20bOlBRUcHYQc8hmmDWgs9o3X0ovbrEoVKp0Bt0zFr5OYgi1YIRnF34fP12Eh6JxWChe+APOe/NGaNPAD1+r41fZt6b/7+ZeX9bIeobypn55kzqdXqmPtqEqpIKhrX05srJPRzJraVTu4dZt+4TPv9yDcn7DrJt82aMBiOrth1h0thhyExSMPtjI0YAMkwGHU/2aoWruzv6esnP7BfoTmZJLSa1ZfUT/+ia2BkoEkUx/RfXmgqCcEYQhP2CIHQ2X7vrzPubzvvq8jLWeuUxLUYSRpuYlqw+nsU1rRJEmD/vLYKaSTE0gxOGcDwtm4LKerav/xiNygalWlpMQ7ztcNAYsHVyRalwQK1QknY1CwC1GpqFdsLQUHHL/twOf3SzPZz/T8BwzzPvVXau4sgjqZSUfc/sV2fxn3gneh6X4VpWBQJ07tn+p6bKS4t+aqOsuozB46ZRcOkkW/YeodP4ntg5yqnUVlO3PROtrhFbG+k5u8BRfPb5J9jY/o8reQqCoAAGA21uXjPH4GjNn08JgvCHM++9NDreGNmGivr21ABd5+3GsEBANIkUpx5EbKjhxo4lQCdiW8UgEx3p8lBXZDTy5LPPcf6aZPL3Tj5Ly/6T8HVV8b7fZew1MhwD5ICRlO3rmPz0cF58fb5Fsvgj07kXkCqK4k/T9H5k3js4eXHwWgPRLSVd1TqsNR2jerDohTfp0KUvDw8cx6NLpM22tk5OUtJuGvVaftiWxKQh/ag/dxqAzk8+z9wli+g7fhItPG15pF003eMky9CM6cMYP/YxXNydLBKEpc57kKIYfs2l0gU4LwjCOWATMPEXpfEnAauQyulncAdKBaC6toZjKScxaKQfuGjRYGa+0BvvZoW8GuXOB/0VvB0mTagtSYdoKNVx/PAeNJ5BODWNIsMgraUjprzEmBGjcfbyobRRReI3u5izQKqzXVCupSDnGp5unrfuxG1g9SeWB0bZewBRNKEy1bJuhRR4pk/L4fzlDNKvZlEfMxF7dydu5Ep7e9t2w9G0G4ZP5xGM8SkmQXOSGLlEku1Re56vPvmAQV3CiFz0Psofk9CdkiZSmbw11eqOyJSWlf6zeiFqtXqahYfx/jqpfpGXRzntGuqxN9kyIqSIYYMS6N5bKva0f9XzuBUdQC6XcT07nU0Xs+g1WDoXlBs8GPD4Y5zY9y06vRHPDi14/OnpAPy44RW+/uhFqmssc1RZvT2xqrqSpydPJ+lbSQ+dL1QRHBvB+gULCIpx4/ixU+TmFtC//0BGv/QRzmqo14so7Fzo5GViX2ISOHRHbyyhfZs4fANCQOVHyBOPSkbY00U0Njji7B9BxaUdFvXR6tfEwOBm4rBnJ5GbmU4Lb29Ky+o5dG47L0yZyIsTZ4MAXy3ow74b4Vy+koZv02givUX8FRXk36gi9VIedu3asef7U7SJ9CP56GGeGjcYg64Bk8KB2jojh6/uAoOKM/vPUVpU9fdbE00mI8cvXMSEVPPL0T+CQztTUNqFUq8zIJfJeXHeIQAOHTjMxjUfsnrPZdavP0bH9jHEt2kKQPIHnsydNQw/Dw++33uI5avWc+60tP1JvSDnUIoBZPYW9dHqp7OdWk3aif08PW8h186d49j+jTybeZKiK6fQ6w0808uXby9JlOxbN68nK6cIZxd7UrdsZMfuYxhMCghw59Cuq0z7+gWM2kbatm1NN79Adu3aTUhoDKUZJ+nUtSdVJbrb9ObWsPrpHB0TLS5evpyI4GZ8/PEKnANb4eisRKtwpPD8BUI87QnydmXf6ROs/Wwd9fX1GHR6Ns5/mZmLP8Xe3oeufbvS+/AWZiu8eSbnEtdHD0cUbTEpBAw1IllpR7F1VrNhw49UVNb8/aZzXl4BqxI/Z+dOaauiUNlQpxNorK8j1EfAzd6Ih0oaibXVNWAuxpmr1aCrLCNcovTjbIgv146nsMDGFVe7ALKy9fibqUt7xETQs0UzXJ0tO7FY/XQWRSMejg1czTiFWulC17znUcV0xC8qjqmzT+Niq8JOJUfm5ILBYCDQ1xv3QD8OHz2JxjsEjUZycCX8ZyXB7Xbi6B1A+uVjPNYlEoXciaxLJ3C1VZFbUYNea1kKhtULUSaIVJTXkJ9fRlR4W8bubYl+TzWN9Vuoz0klNrIFDho1oTEueHn5EN62PS72DhzMC0MT1YNBE1vyw+6tbDs0lWoErhy8waT4l3B0dQCdSApQo/EjokUQqrV3dBL9L1i9ENVGDbW5Bpp4SUfwAQ954uoaTMbhDeyTq9G5VpB2pZDQmFYc2bECmaM9T01+HrvCb3koOJYTW/eAOoSa/L44apTERyjoljCS2Ogwlj4bD3ixcu37NPh0oLTSsixTq18Ta3V1DFk0mJC6UgBqyp05k5KCY5v3ie8zmoSO8byw4HMA5K6eLJ27HH2VDT1im3BuzwWKzacQR1sNB06cw87Wlg/f+Rebtn+L98PjAZg7p4H3nj6Kr9fflK5do1RTqyvD1UMK7my0jcUxcCz19VBVmc/VBkdczBGuCoMWf7XA269MJdugJ6CVN9mpUrpNTW0t7aPDKSoq5Jl/L6RNq05EtZbIwwYPMzJ4RB1G0dGiPlr9Fic0PEx0drOj62NPYNvYwJgxYxCNRkRBIOmjV0g/fxYbbx/cgrsTHeZJvjGE54b3Zv8PyQQEeqEzyfjyy41oPEKQy+UIgkCQbQlph74hpEN/UrOr+ff0YejrtTSL6U5xSfnfjxnIqKtj7tR3OXxZCvFIXD2cQJkbOWI93208jo2TB96yWtyCIc+k5vDUUeQs1jBk3gfkZEN+obSWXi6V4ezfAvvCI/g4F3M1o4YVa19kwsuzWf3xFA4mG7HVWLbZtvrpXFxawrdvvkntcSkqrHP3xby6+Ag942aAcyCD+nXA3UkyvKa/+jpyjYadRSJllTouZ+QQ2ERyYj3ko2X7wicpLClArnEitks31n4tpWB8sSuP3JpyysrvUzUSQRACkHzO3khb2ZWiKC4VJPr1L4EmQBbwhCiKFWbz/1KgH1APjBVF8bS5rTHALHPTc0VRXHu7Dv5djLIG4F+iKIYDHYDnzBn2/xPOe7mqHgfvk/Q3Hy+6hfrRwdeeOXPm0HbALJq2fph/PDVVuldhx4DIXiga1RjyC/lq9QZWLpZGm6OHFzfKb5CWUcg7C5chKy6j4KqkdCLFYsK0eSgV9ylBUhTFgpsjSRTFGqQwET+kzPmbI2ktP5fB/4nzXhTFY8BNzvs+mDnvRVGsAG5y3v8uDEYjx78o5WKeFMXq27ILDho1BfnF5GWX8Nm6JNZskApUHvvqO6bNep66uhL8A7zpv3Qy1/OuA5CYuJzC/DwyC2/gH9mSqzfScHKRloFLOWfJpBLJWXn3uCvFYo6EaAUc51ec94Ig3FPOe8xl8zW2Cha+1IGhSzfQ+8lJNI8MJTi8GXKZjI1rp5OXe4XqmhL6dQzm9U1JFBZn0Tcumv/MHk1tY38M5tUqbsw/qTmXwfmzO3jro/kEODtSml3F5YunEVydqaoqoqziPlu2BUGwBzYD00VRrP6dQjz3hPMes/M+rHmQuFdnIKi5pCCmPzOBWQuXsfOHAwwdb4NK15EaoZaKC7D/08mEhsaw5eyHeDXtRubmL1hdJoUJvdSnBzYD+pIzdiAxrSKQmwysPyVNpOmvb+S7nVtpuj/3Vt25Le5IiIIgKJEE+IUoiknmy/8Tznul3EheaRX2AeHm1rOZGRfHOUcHojq68I+HR5F2cRMaIgkIaUduUQZ2CjkOEbHEVJYQ3zGCbduKMBqNvPzyy6Snp9Pv4XjqTU40NhTi4ebH2sUTqS7TUll9n2pAmLXtp8AVURQX/eKr/wnnfU1tHdqqLNIuSMn9fnEdcerdmYe7dcTLyY3Uy8dwd5VWkqOHt1JRUoRSY8ONG+X4tQjjm62SUWHOnDm4ubnRu3dv8jIyECszMJjZ0fyCW5ArlFNeU3brTtwGdzIS44FRwAVBEM6ar81E4rj/yuzMvwEkmL/bgbS9uYa0xRkHEue9IAg3Oe/hDjnvjXoZPq5hPDPYjmt1kJuZidwlkDqtkuT162jVezAVJUXEtvbgjXkf4uwmAwEGTuxGmVqOj8aWevtRpO7/Dq2fO3qNHFO7dyhTKVAqFfhwlsPnTtAuqgvb7C7erju3xJ2E1h3i1usZQM9b3C8Cz/1GW4lA4t10UCaXIXd0Q6WUNGlJVQXhfl58/+M+4no+zrj4HuiyLvIjoLbR89ar7zJt6nSKsowIIUpOFVXTIwo6DRyJWqWhNv8MuYUHievQHlu/SCovneVsSjUXz+xAbW/ZAc7qTywymRyTvpFGk3Qk8/cLJsjTgyZ+XgTZueDoE4jRrJ9UgoKpU6Zg726Lo5scB72B8eadqKe2jDBnBW5qHXH9xqBzi6CyQXrOM9yVrgmxFBVYpp2tXojIBezcHLB3luKpQ8NjqdPJ6d5jIO4xoew8l8xJR6k+trZRh86gJ/VsOgXlOmR6GxLzpBGsUak4vn8v3eIfRSaTIQgCMvMOQymWcvVENt6eltG1W70BQiZX4RPQDq22GG7kkrTiXTy9nTl59gpNYmLJE+U0Vtcy9LF+yN1jccCEna8RL9/xXNfJae0vEcLOPZpD30cSmL0nm+qsUTg6KjAJcgZ0H8Q/Og/gq/0/UFRhmWKx+pFooxFI+uRz1qzYDkDCiFgK8tOZ/sJjZGkN2NkoKC6RDLZ9HxvC6q++RiZXUlFezrDep/HzlEbbtW0bmdTNk3MXTiKzEWkR4IepXDoFJW1ZRPeWbXDWWGZPtPqRWFnVQGArV7y00ppYVtVI09hICspqadeqB8FOGurzpEDOIF93LqScYqu9Cz7Vdhzcm82Fin4kxEHshATU9vYIlYW4N3dCpqxFUEn7wkKVhv1H91BnYRFKqxdidXU5509torpcQ7teE2g5cC6PetjTIjiAnVtWobBxwlAjkTQkrv65ZmypLoCY4Fm4OijZuH4ZA511yMRaTJ38+T4jl8DoFrgGSyOxw1PH0esNNB552KI+Wv10Fk1GWjaJ5NGoMAAuHtzGknffYt3Kdzl98io5n+2m607JYNuxUxe6PDKQ4cNHoFE08N6bL1BQLE311+YuZnNKMa0GTsbFxx3dkVx8zdO5ojiHGa3tf6qbc7eweiHaqtUkn71MaAvp7FxWXkNmVh4jn55BfYOJLbnXKZozEoCjRw7QqkUzNmxYj0fjRWIjmpC8VTKFLVu5jjFD+rAxaTfx3TrSNsyfOS9Iz+1ePpP4KW9hLL+jMPL/gtX7WP4uRtk/FYbGOlzrSnGuknKTv9y3nkq7HJpENeHogVRGDZ9B+mUpjSb7WgqNWXtRVZzlmQkTOHb+DOmnpLOzbUArdhw+wtGsNL5csxattoENG6UkscWLl3Lh4gXkSssGlNUL0dUrEJO+ke7jpIKR/3pzNO3bhiM4FiC3z2fR3GfQ6aT8lUE+2YzqVE1OZh4KnZZ/jhrD/nSpZs7qD96mKrcMX9umdOnSlTfefJt9+6SQvAUfzOShuEepqa+/dSduA6sXokKlZNzrH2KjlpSAsVjOhfRMsgqLcNbY0uDQgJdK4iBddcTA5BWN7D15DaWLPYGB3syfLxmeTPbe7Nq8mmljHqdXFEyZMoFHB5gZhep90ShVmBrvEzXxnw1BEGr4OWv1fsEdKAWCRFH0uNuHrX6fCKSJotj2fr5AEISTf+QdVj+d/wp4IMR7gL+CEFda+zusXrH8FfBXGIlWjwdCvAewWiFaSj1yi3YCBEHYJwjCFUEQLgmCMM18/a7pUH4Toiha3R8gR8qJDgZUwDkgwsK2fIDW5s8OwFUgApgDzLjF/RHm99kATc39kP/eO6x1JLbHTD0iiqIOuEk9ctf4nYCs38JPdCiiKGYi+c/b/879VivEu6IeuVP8KiAL7o4O5TdhrUK8q+old9TgrwKyuHs6lN+EtQrRYuqRW+FWAVni3dOh/Db+bCXyG8pAAVxHWthvKpZIC9sSkMKll/xa4fzi8/NI6yBI/Fq/VCzXuY1isUorjiiKBkEQblKPyIFE8Q6pR26B3wrIGi4IQizSVM0CnjW/+5IgCDfpUAyY6VB+7wUPjn33ANa6Jv6l8ECI9wAPhHgP8ECI9wAPhHgP8ECI9wAPhHgP8H+HJhgtu6TiOwAAAABJRU5ErkJggg==\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " ship truck  bird   dog\n"
     ]
    }
   ],
   "source": [
    "# functions to show an image\n",
    "\n",
    "def imshow(img):\n",
    "    img = img / 2 + 0.5     # unnormalize\n",
    "    npimg = img.numpy()\n",
    "    plt.imshow(np.transpose(npimg, (1, 2, 0)))\n",
    "    plt.show()\n",
    "\n",
    "\n",
    "# get some random training images\n",
    "dataiter = iter(trainloader)\n",
    "images, labels = dataiter.next()\n",
    "#vis.images(images/2 + 0.5)\n",
    "\n",
    "# show images\n",
    "imshow(torchvision.utils.make_grid(images))\n",
    "\n",
    "# print labels\n",
    "print(' '.join('%5s' % classes[labels[j]] for j in range(4)))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [],
   "source": [
    "import torchvision.models.vgg as vgg"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [],
   "source": [
    "cfg = [32,32,'M',64,64,'M',128,128,128,128,'M',256,256,256,256,'M',512,512,512,512,'M'] #16 + 3 =vgg19 ; cfg 리스트를 VGG19에 맞게 수정"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [],
   "source": [
    "class VGG(nn.Module):\n",
    "\n",
    "    def __init__(self, features, num_classes=1000, init_weights=True):\n",
    "        super(VGG, self).__init__()\n",
    "        self.features = features\n",
    "        #self.avgpool = nn.AdaptiveAvgPool2d((7, 7))\n",
    "        self.classifier = nn.Sequential(\n",
    "            nn.Linear(512 * 1 * 1, 4096), #512 * 4 * 4 --> 512 * 1 * 1\n",
    "            nn.ReLU(True),\n",
    "            nn.Dropout(),\n",
    "            nn.Linear(4096, 4096),\n",
    "            nn.ReLU(True),\n",
    "            nn.Dropout(),\n",
    "            nn.Linear(4096, num_classes),\n",
    "        )\n",
    "        if init_weights:\n",
    "            self._initialize_weights()\n",
    "\n",
    "    def forward(self, x):\n",
    "        x = self.features(x)\n",
    "        x = x.view(x.size(0), -1)\n",
    "        x = self.classifier(x)\n",
    "        return x\n",
    "\n",
    "    def _initialize_weights(self):\n",
    "        for m in self.modules():\n",
    "            if isinstance(m, nn.Conv2d):\n",
    "                nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')\n",
    "                if m.bias is not None:\n",
    "                    nn.init.constant_(m.bias, 0)\n",
    "            elif isinstance(m, nn.BatchNorm2d):\n",
    "                nn.init.constant_(m.weight, 1)\n",
    "                nn.init.constant_(m.bias, 0)\n",
    "            elif isinstance(m, nn.Linear):\n",
    "                nn.init.normal_(m.weight, 0, 0.01)\n",
    "                nn.init.constant_(m.bias, 0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [],
   "source": [
    "vgg19= VGG(vgg.make_layers(cfg),10,True).to(device) #10은 클래스 개수"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "tensor([[ 2.2050e-03,  1.5503e-03,  1.6003e-03,  1.4452e-04,  1.0723e-03,\n",
      "          2.2150e-05, -1.1437e-03,  2.1674e-03, -5.7780e-04,  1.1803e-04]],\n",
      "       grad_fn=<AddmmBackward>)\n"
     ]
    }
   ],
   "source": [
    "a=torch.Tensor(1,3,32,32).to(device) #텐서 크기가 배치 크기 × 채널 × 높이 × 너비 인 텐서 선언 \n",
    "out = vgg19(a)\n",
    "print(out)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [],
   "source": [
    "criterion = nn.CrossEntropyLoss().to(device) \n",
    "optimizer = torch.optim.SGD(vgg19.parameters(), lr = 0.005,momentum=0.9)\n",
    "\n",
    "#lr_sche = optim.lr_scheduler.StepLR(optimizer, step_size=5, gamma=0.9)\n",
    "# 5 epoch마다 learning rate에 0.9배 해줌\n",
    "# 그런데 우리 과제는 epoch=2로 트레이닝 할것이라 안해도 될듯...?"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Training"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "98\n",
      "[1,    30] loss: 2.30260\n",
      "[1,    60] loss: 2.30261\n",
      "[1,    90] loss: 2.30260\n",
      "[2,    30] loss: 2.30254\n",
      "[2,    60] loss: 2.30254\n",
      "[2,    90] loss: 2.30255\n",
      "Finished Training\n"
     ]
    }
   ],
   "source": [
    "print(len(trainloader))\n",
    "epochs = 2 #epoch 2로 설정\n",
    "\n",
    "for epoch in range(epochs):  # loop over the dataset multiple times\n",
    "    running_loss = 0.0\n",
    "    #lr_sche.step(); epoch=2니까 걍 안하기로!\n",
    "    for i, data in enumerate(trainloader, 0):\n",
    "        # get the inputs\n",
    "        inputs, labels = data\n",
    "        inputs = inputs.to(device)\n",
    "        labels = labels.to(device)\n",
    "\n",
    "        # zero the parameter gradients\n",
    "        optimizer.zero_grad()\n",
    "\n",
    "        # forward + backward + optimize\n",
    "        outputs = vgg19(inputs)\n",
    "        loss = criterion(outputs, labels)\n",
    "        loss.backward()\n",
    "        optimizer.step()\n",
    "\n",
    "        # print statistics\n",
    "        running_loss += loss.item()\n",
    "        if i % 30 == 29:# print every 30 mini-batches\n",
    "            print('[%d, %5d] loss: %.5f' % (epoch + 1, i + 1, running_loss/30))\n",
    "            running_loss = 0.0\n",
    "        \n",
    "\n",
    "print('Finished Training')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAXAAAAB5CAYAAAAgYXpDAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4xLjMsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy+AADFEAAAgAElEQVR4nO19aZAl2VXedzPz7a9e7V1d1XtPd88uzYxGIwmEEBLYIwESYQssTMCELcdEOFAYHEQYYX5gRfgHhB1gHIHlmEBCAhMIWRJIFjJGjHZgpOlZpZmeXqbX6q6u6tqr3v4yr3+cc/OcV0t39UJXP7hfREdl38yXee/Nm5nnnO8sxloLDw8PD4/eQ7DdHfDw8PDwuDH4F7iHh4dHj8K/wD08PDx6FP4F7uHh4dGj8C9wDw8Pjx6Ff4F7eHh49Chu6gVujHncGHPcGHPKGPORW9UpDw8PD49rw9yoH7gxJgRwAsCPAZgE8CyAn7XWvnrruufh4eHhsRmim/jtYwBOWWtPA4Ax5tMA3g9g0xd4sVi0AwMDN3FJDw8Pj398mJqamrXWjq5tv5kX+C4AF9T/JwG85Wo/GBgYwJNPPnkTl/Tw8PD4x4ePfvSj5zZqvxkbuNmgbZ09xhjzpDHmqDHmaK1Wu4nLeXh4eHho3MwLfBLAHvX/3QAurT3IWvuUtfZRa+2jxWLxJi7n4eHh4aFxMy/wZwEcNsYcMMZkAXwQwBdvTbc8PDw8PK6FG7aBW2s7xpgPA/h/AEIAn7DWvnK959m39AUAgLFJ2pbNULdMIN+XVqsJAOjEbTomm033xQn91iZiwTFBDAAIQtXndon2gfZlso10Xwh3TTlHnHQAAO2O9C1J2HJkIu6PWJKavE/blhIelzHS2mrRGOI4Wjf2gPvWSqStSt1ArRWnbaX7noDGhz/84XS70+msu+atwHWfz675q5sC3UatgWvUhjjj5i9Rx7t5lpNczZtqo3674z/2sY+t27fvh3lu407aNnflMgCg2ZA1c/CuQwCAgf4KACATSn+yGVp4Wd3G6zkyao116gCAcinD55C+RrwdqkW8sDAPAOjr60vbMpkMn5eOM4Gco5O0AADBBqJaYKSxViXzZhTRmszn8+m+VovO0eFnEAAK+QJfS/r2u7/9W13n371nR7pdHjlCvwvlua30lQEAK01Z19XlOe4v3e9ELYaIB1GIcmlbPuRXmHpu0weQm+JEzu/aEtXmruHGTtfnudxg7Ri+fybQ74V4g+Pot7kc9TcbSL9hadtkZf5qc8cAAF975vvrzrUZbobEhLX2ywC+fDPn8PDw8PC4MdzUC/xWoMVSlLV1aWTpM4dS2hSAvlRRxJK1lij4q2oy0th0UkMiX7iIJbyQmyJ1DpOQVIyOSBlOGk7UOVqGJJM4pC9oS++LAz6XfI0NS/F51beIJZ8goo7H7bbqSIeHJOdwEmcYbm7xCsNw0323Cjcq0ev5SOUkJSUmTmSyPAYr+5xGZCDSjpzl5iXwjVAu0r0NrDwezSq1JS0h4vNZOm+pQMdF6jJu7eTUIitk+b6rsTRjdxytq6xaJ26KokjurZPsAyXFu7nJsVaql0m11uZrCpz2aiHnDfhiGZZCnVQPAO1mk8enxsJSJa6yJhIrUnwnHKRzZeSZjkOSwIOMksDrq9S3uMr9kPM1LR3XVpJvg+dXCeVotUlLCviZqNfk3eKeEz0+pxEHgTyH1mkuPJla4+90Yj5GrmmMez/JmhkcpDHnCn18frlniVvXOelHvFrG9cKH0nt4eHj0KPwL3MPDw6NHse0mFMsmBlgxXVgmj0wsKl7SJpUmLLCZQqmhznqgiYQsq0gdKypK0g67jnOqEAAYu4ZIA2CYcLGhqIL1mHS1y3OkblVbohatrlJbaOW8fXkmsxQJVykSAVTI0TiToJXuC1JziYzdjaCdbK72a5PA31eZvK2ct8tc4Y7v0jXdLm3yoTlvtmk+Iq03x/Tb0Gx07WSDtq3hamOJ2IwVKDNWNqRrZQJpywVsHnP7FAHZrJOpJQwV4RbRfW83hQgNwCazDrVZI49kzKaibKYgx7t5UGvMkbkxmwF1vMXclSsAgLGRQTmezSVhVq4V8rXcPCtLDiI+vqlIXUewttvSthaBlX0x9zdWz0FsaMz5PunH8L4x+u3SAgCgXFtN97Ua9I6Iy/I8Jv0U2d2Xlbl31w3YztpqyvPlHB7yebkv6ZSqNeHWsfsbKJtth8ec6OXHl89GsnYLBSZ64cyAYqJJnHlWy9A3YKL0EriHh4dHj2LbJfAoZsk7lK9fwJJELlRfd8cQ8Zcw0EwN/7SjJVRHymRFetm5/24AwPLiLABgdk4klUxE0nYA+TK3OjQ9dSsBSMfOkURjc8MAgHYopEyLJYPVpfm07eI0SxJ5JVlNLQIA9u6kaw73aSnNuRbK2J1wEdv1rkoOWvK9Fe6Dt0SKT/uttAN2tewo8aXNmtDJ06cBAGM7xf0sYTJ6dEgkyDwTP8lN9PFqc5RlKTvpiOQWsvSUUQRahtuCmNZRNqOkupBdVZV2lQno3iZGaVwJu8c2mMxU66nBYy8WZQ2HjtnU4h/PQ5VdHJ977vl0V5s1gcHKm9O2XI7JfDUFqSsra6eBct8z1pH5siZt4oi8zSXwDsTVMQCt9SRUBC5rYaHSxkrMRlaKfI+ffzbd15olaXz8gbulb1fomWsambcyD2ylTkRoXo0lxxp5MCyEYcAkpn6lNIt03qjNmklbJmulRPclt7SUtkV77gMA1Ab607aEtaqY71k+ESI01fhjaQvj65envQTu4eHh0aPwL3APDw+PHsW2m1Ccnm0iSTPr1NuOjlBkwqjFam1WkUNx7NQ5ZWLgc2i/2rf86I8BAJ77278DAFxiUwoAVDsuslJUq3OTMwCAM5MX07bc4DgAYPfYAbpmTtTEFqt/mbJkfew0SO2bm5E0McVBMr9MrlJ0X0Opw2N9pOIVM6JWxm1Sg3Ww2Vr6biMS83ZEYl7d1MJkWUZFzbKPd31VSOvFJVJ1p2fJ9FToE3V4mCMOddSgI+10dOYGnV3Ti60jy+Y6q86RcZMfS79DOLKd2jLKr7rt1OdEzhFWaB6MVX7/7G+cuGjfWNb16jKZ2spFIe0Cnm8dFRlx5PIik5fzy2IaLLCfdEtZOlptulaU1WuG2mKOdO4o85GLgs4qH2fLazaJNzfr6Zl3JsFAjT3u8FiV7cKwiaNh6L5nElkLZoRMa7UV6Vv7zAnqrxEzU8LTVXX+5er5yrY5fuOCItF5PrRjRIPNoWGD50ouieZO6mP9sphK+ww986Z/RMbH120HjhhWsQ8836EixaPg+k2CXgL38PDw6FFsuwTeDOhLu1RTEVosvQyWRWyoMCkUsQSiCabUDUgRKo7krNUW0ravfonyrkwvkkQxvSrfr3MX6bhzlyTFeZgnaTwOK2lbqUJf2kyR9kV5+fLnWErMBzKW2RZFgY3v3pu2NZhcOX2aJPD5RZWTZRedd/+oaAIZdqUzyo1L5C8er/q62+T6ZM408HEDAUBL3cEGEnjMUlbC0oaOFnURblfmltO25SqNta7zX9RoNEGOyOJqXe5tucgSp+qbk+e3qmBcryaSM87lTebbkZcbugAmHPmnXAAj1hgjxRSGhubDxvru8fiYuI+Vq9nqCs3beX3NyEUui7S4p0Lz5lwGX3r55XTfG+6/HwCQaBfHmOY3r11sWROo11jDjeT8HdYAw0jI/Dbn22k2N08RHSvpPOE1bLXMyE4HLe1uyNftX+G5Gh1L9xV27KP+WCEPwa6QdmRn2lTPcG6Ty5RXBcolt8rPqx0bTtsyCfWpoTT4EmuBrRUaX1PnqClwxGtV7ks0TNqBySg3Sc530sc/DZWE3zE09yZQLrO4/mhqL4F7eHh49Cj8C9zDw8OjR7HtJpQrdVIb5ttCYn7jb74OALjviJgifuR+IgcG2V9ckycuaU2g1JGYyRLFfeHMOfIznq+TamOLQ+m+sMxk2ZCo+wWu39lSKURbTJxVBqlvlbL0ceYymUSWFxS5wSpeviCmlvMLRJ5mKqQezkxJtaTy5RUAwM6KHF9wqWsTRX6tQbWmk4GxCqlUR5dqN1SJkdy2S4+pckghSNZ/212UqLZdrLJ678jMgiK6GhyxNqVMKDMLtJ0ogqvN9pHaChG+M7Myf5MXpwAA9x0+mLbdtX839V/5xadkqouk1VYT120dJnAVajNkE17SFvNAwCa7+pKMBWw+sJwEKSzI2LN8r7Jqvk2bTGexNjtwtLFJiVMxH1WrZCqYnpbjS5UyX1Ml8uI5b63ScXnlj35lkYjQ578vZpVSjq556KDMacSmnGaN1l8hUomXmrS2YpVWOXaPWkPNx1qoKXYpXZOuWA3ep57lDJuvcqdO0umf+1a6r/NmNj2ptKyWYzSyK/JsNEDzUOZ4izAnxyclOr+xiljnZHJ9w/IOylxk88sqrcnMmDgr4ALtiypi5mxcofkNi9KWHCHf8AYnwgoU6Z7t0OREyjZor8LJbwYvgXt4eHj0KK4pgRtjPgHgJwDMWGsf4LYhAH8KYD+AswB+xlq7sNk5rtqBfpICanPyLWlniSicr6lk5y1y66lk2e1KER9O4gxDIVkaLZJgryi+aHaFvr7FASIwBkeFWKwmJEmMQEW9MeHRyohU1KiShNJYpeP3KTKkxtL2TEukYcPS0NK8krpYGqnz1z3MSr+nl2kap5ZE6t83whrGVb7Qi3UZaLlIWkGg8jK44hRdgrUjV1yQa1ca1w2+7Ru4J16eIhfLoSHSZgp5kWyaDRpzMSdtO0dJk7JKPKvWaKwlllRaDZX+kwe92pTxddI8FcqtLXVndPvWDbNLIrya92PeJexXBzkJPKek/jKTxf1MPgXsDgkAOb7HeS1wspYUNGQtpEn+uTBIa1nWWl+J9g0OiaZ4ZpK0vNMXLqdtJ049DQBYmCWJc7Uh56i1qcZKBOUWyJL9g3cfSdve9+OPAwB28Xpu5mWcjWqVfyfXrHCBdFNfwWbIhLL+XDpoR2YCklI1UnJkeYGu1Zkkt9uK0iZWLtH1W3mJdrSg94K5PJO2lSaYgKywZgl5lgrsvppdlH43mDjuzE6lbVmew84yzVVuXhwZ2nXWlgqiwSyeIeeHbEEk8L5xIl1dKiWrXAabjrxWa7iVXL8IvhUJ/JMAHl/T9hEAT1trDwN4mv/v4eHh4XEbcU0J3Fr7TWPM/jXN7wfwTt7+FICvA/jVG+nA3W94DAAw+czxtK3cT1/3x972lrStGJKduMUSsJYuDWdri63ky+jbQfWWX3z5pJx3gKS/XfvItcoqW1qGpeykOZe2tVrJumuF/MV85aWXAAAVlZC9WKIvf0nZwS5dngbQnaclZKliiN2/FhfEfrcwT9tnpsRVamKMXKSirIomWIOoIppAzNJzW9eTY9ti+hdil3TBIVritBv4FDoBXXkspgElLl8GlCvnALtitdvqXCyVFctiU3QSuOHgLKNctnIF526lyoQxsdFlM1zXN7lmpvsQ3r25CH7h7Fnut8z3yjKtu7gtmsDFi6R9LPAaqK6KPXjHMEnN5ZIE4YRcjKSlMvhFnKsn4Fw8VSWdN9xgVGGJ85eIPzkzKTxBtUW/zfezK1tJJsatxFJWZLWpcxT8cunSdNr2rW/9DQDgXuYaRgdE4qyvkmTvyp0BQPteykeyurS54p3Lytitk8YTpRKzBhMot9dVDrxbffSNAIBK9KZ0X22F7kFb5U0yOZ4bVW4wU6DrVtldUru/tjnfSEY9G3WeG+3EV2e7fG2VrlkqyFgafHyuLM/5UB+9e2L1rljltQt2ayy0VUZD7pP2+G3fQG6fG7WBj1lrpwCA/+64xvEeHh4eHrcYf+8kpjHmSWPMUWPMUZ2n2MPDw8Pj5nCjboTTxphxa+2UMWYcwMxmB1prnwLwFABMTEys0xGK/aT67zsohEqdLQp7DxxK20ZYDV88cxYA0NbRWx0yRTz2jp9K2/YefBQAcODBs2nbcy+Q2WOwTCaJSzOSCyVit6KcLibAvV2tCjm1OE9q5FA5ow+hfrCZZGRUcqG4IgWzC2ISMRyt2McuiFGoiAxWoV+/MJm2jQ6Smn14t3JlWoNP/OH/kvNzPzJKnSv3kQp46IAQt29+A7k5ubKNVpl5HClotb3E5ahRZhJHsGVzdH5NTmazZBIZHlTujK62qaoxmObYyNA5Gh05/yKTuosqdefKEqn0be06ycTjMLuCHT4kBFPGRevpwuVBl0GlC9/622d4uKqgiCOe67IWzl4moi2tXanEoUGuVF9SpG6Oj8so18KIXdwCrolZUwRkxOewKu/P5XkivtuKjS72Ofc3zhe0qtwf+X40GtLvSh+d961vejBtq3IK5Aa7zJ4/L6aR119/ncauXN7OzdHc12ty3ignZDwAlEriENDheWjH+p5xYRVF3hk2KRXGiKhcrspYrizR2I1yj21xzc+sJgMX6Tcul1IuK8/BMq/xfEa9+lyaXxWJ2eToYHDN26W6rEmXhqaoolX7dpPJNtRmvbSeK98rXbvBvTnUokxuwI/wRiXwLwJ4grefAPCFGzyPh4eHh8cNYituhH8CIixHjDGTAH4DwG8C+Iwx5kMAzgP46RvtQJgjIuDS9LG07aE3UfL5Ur980cMVIoxilgIiVQ7q9AUiGt4+eEBOXKRgj76SqiIe0bUK7LaXz6pS1vz13TUxnja9ypJHVpExy0ykHNhDGsORe+5L983Pc/GGigQEXGL3JqNIk4FBklqXWLrU+UMKRfptfUX6ffI8B1coImpMUj/Q8TUVbFSn7YwKqllhAbao2uJ77wEANCyTPUoCz7EkpKVWV5hBZ+nrHyJtIyWKlPuhc4sKlbTtIqu0rJGwNHKWA60uzohCNz9HGk+9LpJb3GRJU+VMcTk5du+h4Ki9e3an+0rpWtEk7eYS+IsnqR/Fgmg8ljW+ZkfuSz9nlXRkXUtJuVdW6R6Eaq768qRxdWIhrQ2TdiH7mplIAsNyVZIcW20hR+fnHXmpy3/R3xbnWFmpyly12L10z6i4Ig4P0uJxgUIAML9AeVSGB6gfj77x/nTfJLuKLtVlDb82SfclUOv6gKQtAQBEKhNooY+euVVVIi1ilSVWWfgiDnYJeE0myv3RcIGXSF3TbbVbKgMja9ERS9Za43HkZay0PFeqraNWZabAJGO8Pqupy52S6ShNgBl+ndEwH7sMlnwtteRcIFu3V+/1Zw/dihfKz26y693XfTUPDw8Pj1sGH4np4eHh0aPY9lwomTwRKo2GVoe5/qCKUCyWHClEqr2ul1mOSAX65FMfT9t+8l98mM6hoseyXAvQFYc4cHBXum9mngipxqqowTt3kN+4TpDf5DqFBw8RwXrXISFfl16gWoTVFVETHQnTURFodTZxDHD9vNhKVFj/IKl/HZWBPwxofJOXxLQw9gZ04Wf+2T+XPjK5V1L5VxxpUlCmJ5eaYXmZ85N0RLXPMKkWKf9Xy6poXflH24TO56p2a+I04uMzGR3hud4M4/xfG5w/pKRyTAxyPpq4JX3LhzSuxTkxAUxePAsAOMTEdxgoU5F1FddVyt2ruNwus5nOaqKQffsLoczH7j13Uf9d2tzLstZm2fQzNiYetrkRMutUF8WfOuFI0/5Bsj/kchLL0OAh1zpiQsnzcxC3ZY2FTAa6IieZrCoskaftxx4Rk8iRfRN0/pas9TOv07heP/4qAOBtbxaCc88eOv78y5Kzpx27nESb18TMqn5kuSZsYsVsWWDSuqPS9q5wJGrMRGW+X0w/YyU2aSmyTyq+q7S9cDU/6a8uRLERLD+b2oQSs6+5S9sbqGtmneFGJVpq8jtF516K2IQYcwX6rrq1/NzouqTalLpVeAncw8PDo0ex7RK44QitmpJ8GyxBZnQehDl28eF8JxkspvvGB+iLePKYRF1emjxFGzUpZXZu8iwA4OGdFP25a58wgRMzJAFVT4mUMZQj6a9vQMokvf76GbrmBEnvi8siHbX5Sz59RUlYjtxQroI1lsAN50bQ1EXJZTdMJLIya2g+WrOXsRmStkgIqQSi9pezdN5CXua0zpnkam3qx9nTZ+WaTGLuPbAvbTtzgebyS3/5dNrW5gyQec53UlTnd9Fr/RWJ6hvoJynq4YdFhRgdIanzrt00p4Fy33NSlCOaACGn6jtEOpsYp3s1sYtIaJ3hrsauZl0ayVVElwwT66M7JtK2PBPIs7Pi3lnlqGAXTtdQEZb9o7S2dilX2L5+GmdlRKTyOSa+Y5bI2qpCmXNZrCnir9V2BKVoJFmX8TJH9zhjRUPawXM/Oij3IM+E3OigsI4VdrWbO38eAHDu9bPpvp1DtP6Xpp9J2zJMXrfCzV8hkcr9EXKWxbzKj7I4Q4Ts/KrkILkyRfM72Efr/4H7RBPIsPbdVARumzUATcC79e+KnASKWHdSsC4FGKfEqWYZu3Pr6EynSM8hz1zEx+u1636TcZqRftD59IFyiYyv4tq6GbwE7uHh4dGj8C9wDw8Pjx7FtptQ0lSwSh0ZHyH1SavjX32ZfLIHOan84SFRafI5JnEi8YW+MnOWTt+UiLK9d5GfeMjnLVaEMBoZI4Jpbl7U1SUmL3Xh7R07SP2N2LzTUGSjS1JUV+p+h3/cUSdpNDlVZYe+n8NKpTZcKy9rZCw5Jnli2x3ppvHn/+ev0u2EE9QHyoe2zIRwnzJn7D9MYx4dJpPB8LhEaQ5xn/IqGdPiMTIvfe+Y1A2tW1c8gv4fKfW2wr89tFfMMG977BG6Vkl8rEushjsNtqXmtMO+zbUlMZm12Y+6oKq1DwyQ+WCak4fNqqIQBY4IHNsp81wsqhiANRhkk1mozANNLlxhlMwzP0d9Wl7mtMDK5BdyBN+5i5IwqrJM5o/+fokTcP7fTSbxjSL0ci5asCT3vWBd5KbOjUvPRKnA5kVV+X33MM1LURGKVa5231GmGVfs4gCbfI69djrdd+QIJa6CIiwvXSLf8PygmLEAvd1N2rniIokyZ6xwTMWVK2IaXFyg8554+bsAgNde+rt036FDFHOx/9C9advgCJuBlPnBpU52xT20YSJMfchV39LCJqpqPBOQUjhGkaR8vObB08jlDdjxlCTtShbHZ1X3W79LtgovgXt4eHj0KLZdAndRUv1lIZgG+mjbqJwby5YkidkF+hKO9EnXS0zAxIFIHmcvnQUAjA1K8vd9/AV37lnffU6iPy9OkaTeVxapPMNuTq+cOq967CIJ6W9TfTVXOQJuQCXg77BYOTWtEs73UZ8idlUqFkXCcvlD0BYiNK5S38Z2bJ4L5dkXvp9uFzJEKDabQrBmmYR7y1vfnLadu0iS9BxzSA/cL65mWSYga02R4jOsuTzyiBCQDY70y7K0ePigRMPezylHJ0ZE4qwU6d4mym30wmWKApxZ4GIWs1fSfVUmtxcXRQJvcUrXjHKJdLlYXKRuWxGKxQGatwcg4+vv33wunSRdU5GeoXEl6UTqjzk1acQRvokVeSibo/OPjEhkb5nXeF65ZvZzvyO+Z9q90rKrXke5d/azi2WgohcTTpsauejFpkjW/ZyAxXZEK4xZq2mpSMI6348ir81zl2X9vfo6aXfNpkR4ths0vzbUVPnmcFJrPi9jv+duigQ+dK+489ZWSBp/5XlyyX3hqBCn3/omaYDHXpW1fuTehwAAh+8WqXxgkNabI3fDrj66+d0gF7EmR10JuM76MoYuOjNWpGeSujNujq50zcaVgZQ1rFNObxVeAvfw8PDoUfgXuIeHh0ePYttNKC46bucO8cl2NfISRQaO7ybV/CibRhaNpGy1IanZ/SNCFPZX2AczL6ryfjahlDmF7R984o/SfTW+1nJdyK8a++HqzJM7OVKyMU/qXDWnr0lmnteOiz/69DSZA5ZVdObAAJ2wUiJ1OFSkU4aj48LaxbRttET7+/OioKmknACAKxeU//oQmYF27xbS7r43HKbz5+Qcr7xIRNEYq7VlVa1nhusDlipighqu0HHve/wdaVvADtX9/XTcyLD4r89z6t0z52Q+lhbJrLO8JNGnK0wWL3La3vllibDsMCGbUWl+s1wBJ1CRa/0VGtcAR24OKnNTjk1U2YKYqlbrQhKvxTD7cGvf+jJXV0lUOtRMQPOxg/3FjYpCzbLPsjPtAECeoxFDlXfWmUzSKkTKhOJ84GtVWTsuIjCnFqVlc0ptieb74lmZ73l2Ph4oyPFjnHI3n9c1ZNkkEpH5KCoK2X2F61PuGZdnro+rVS03NyfeEpUm1iW9soFuo76Fyjd8YJjSsr79nbR2Dx0Sk9y3v/F1AMCZM/JsVF/g53ZZTGwPvoGq+ezZQ+fS6ZrjDq3xWPUtYVNtVxWqtP6r+yu7XL1YTWg764f2OXeEZnqtLhKT33HKDKNNMluFl8A9PDw8ehTbLoE70q4yKBJ4J6Zu5SJxyzrChQiOPkeS1XJGItwSQ9Lc2C75kr96jNyPfuCH/1Xa9necqL9aJSmw3ZKCDjOXnWucfNNWuYZdpKLeBgOS0HcV6BxLV0Ta6YQk+Y7tECI0ZterupL4GnWSOKtMlnUSkbDaDYpE25ERSW+iTJJSsyNtayXwiydeSbeXmej6yX/yb9O2xx+n5JF//VVxN9zB5N4OrmJfUK5peY5OG+sXSayPt/PKfa/DUouTNHXOl8vHSVI6PyOudC0uzBHlJW1qXx+RvjtYImy31hNHGZWU3+WM0Lkj+vpoLJVKH+9TdRY5H830tNzvRmPz6lBFlj7bimgtsEvkQEW0miRNbUwEZEHV+UxJKiX9JZbbtNzkimm4v4pc6/D97sTS1+U5GoN+cDMsga8ukbY3dUmij8eGaCwDJYkmrrH0nChNoMNndMTpLi5QAAB3c53Mh+6TIhknTtPz8sL3xBFgLXQK5YALLgSRaNUZJvFjFb3o0rEGTOoePiKEecJut1NTn0vbFmZprCeborVNX6T6uncdJpL03vvlHDvGiFSO1Lul0+ZiEyrFbMw1Xt193LAASFdOlvX705TFPA/6FGnxFCXad0V7bhFeAvfw8PDoUWy7BO5yfwyOiITQ4a91I5BCAPkySxKcwe/8BXH+f/ubyT2ssSpfxGIfue1NXZTcFYSO61cAACAASURBVKdOUDXujqtWrbyLqmx37RsWt6+lJZJ8+ssicd59hHIzPPvSawCA54+dkX78yHsBdGdRPH2KJPRFldHQuSA26iR57xsTya3AQRtDQyL52ogkg05rczejhipt9eAbqY/veve70rbhAbJN/+BblP2aJbc+1gQqZZGKQy5S4KqmA2Jr1Un2lxbI7lphiSZRGVgO3v0AAGDHbsnYOL9AmkvfgLgWusx2xq6vGO7sqK7UFwCssk3YqhJYrlDAhSmy3TstBwDaXOxC50cpljYP5KmyttSnCjq4oJ4ZledmmYOLEs5aeMgFvAAY4PwhYUZLl7SttZQW1+eqMffRaEq/Oy2aK6MKQNgmHV9SGsnAAGkwhSzZqCMj62SAtbf+PlmTLT5HTWVbbHEG0IADSwaV5lXkLJ6TimdxheHvv/tw2nZFuX/SubQ9n+3dqm9Z3p3oB5ElU2cjbiltbPee/QCA/fv3p23PTtP97qhyb1dmFrk/JJ0fO/Zyus8FKt11l/R7bIzcGPv6hO8BB9Q1uNp9rJ69DGtcOmjHuRHqOB5rtKsijSo9fVoAQhDeQEGHa0rgxpg9xpivGWOOGWNeMcb8ErcPGWO+Yow5yX8Hr3UuDw8PD49bh62YUDoAfsVaey+AtwL4RWPMfQA+AuBpa+1hAE/z/z08PDw8bhO2UlJtCsAUb68YY44B2AXg/aBamQDwKQBfB/Cr19uBhGsM9g9JEv9qndSWWiwqhyOsXK3DE68o17QaqSrlkuTy4Fz7OHdC1L6LTO687W2UTlan6ezj9LBDE+K2dH6ezCT1pkrmXiJ1tTJKJM/DfVJ78Qqr12fPvShjqZG5YXFJrrWDq9b3W+rPvrK43u2ocBEEIyYRl0K0pFRSccIjHLznoXT7g7/wb2h8sajZx08RkZgYlUOGyc42q3PziyrpS+LywAhd6gp/JxAiamWZehJOk6p7SdWzdIU5koaQQyUmTE+fFNPWGU5h6tzwhkZkPpy6v6Sq0s/NEpFnlUkkYPc0E7i8ICqylwnTvE6lu7qWBhbk2GVxblbG8voCXdNFMQLAwCApnePjlI+jpaL22i0ywyRW+rjMZq66Mu/EHCEZsnlK1150ZpK8qu5eYPfBhlq7CRN/pTK7pap1kuUoRE34OkK4oUg7V+ndkYhtVbRjco4iZGuqhqYjAXeOy/pfi1CZENJtdU0Ynq8u9zr3G7Nun4vi7OsT805KLnYV63AmObrWyoLcxxc4JfMrLz2btg0N033cuVOI253j+/maZFYZVqbVUS5IaxRR7u5zR5n1Okxypm6E2hWRzVdWmdNsstbkcm1cF4lpjNkP4GEA3wEwxi9395LfsclvnjTGHDXGHK3VNmf+PTw8PDyuD1smMY0xZQCfA/DL1tplnbnrarDWPgXgKQCYmJhYx8KtcCKOgsrklmZmS1T5LyY/RoZIOjsRSLa0mXmSbOZC+YL1l+krec8DQkycPkuSnkuar4nFw4eJ1Dh84K607dwUSRyvvPK9tG1uloNCOOn/oHIdm3yFJPapWclBYpiIDVVA0fgecsfax1O4t08krDyXZmo2dKABSUzazWktPvBz/zLdHtxJUtFL3xcp15FBLfWVj5lUc6XDNIniSlXFWkLgtqDrs8+5RzhL5OycuAw6NzgVu4GBygD3RyTZ+TnWNlgKnJ0VwrLJ2kdHuWHGXNYuVLlQinma55xzMdQVw13yG4h0VFBZFtdikYnZSxfFHa/E5PI9qsCAy9hY5PwujbpoTQsL5G7abss4a5yrpKjcMPsrtO5LOfpbUORkxM9YrEjMTqfF51XZLV05r7T4gCoSwFpsWz15UcgkXKJcWznb4twV0jRm58Tl0mUNXFD5aJwmlesTbWktjNUSOP3VxJ5hqVXnCEklaf7rCEMAqK9SPy5flgIQly7R9lJRjsvwOnKkfEnlXylGdJwmtC9yEYmTZ+WdUq9T0ZJOTOcaGZXiHg8+SAGBhw+JxD46Smuh0i/OGLkCaQoWfH317HXSJIeKSP77IDEBwFCO088B+GNr7ee5edoYM877xwHMbPZ7Dw8PD49bj614oRgAHwdwzFr722rXFwE8wdtPAPjCre+eh4eHh8dm2IoJ5QcB/DyA7xljHDv3HwH8JoDPGGM+BOA8gJ++kQ6cPkVqy97Dkg4yH3BazJYQTRGrQUJkCOlZ5iIF99wjfrh//VdfBgDUlsRfvDhMZNOpSVIW9uwW0vPA3VRoIKfU8oN7af/ivBSFeJXrbiZMkEwuCNmzzORrIxZz0PIimWl2KILk3By1De0hc8JcTvkkJ0x6KnOJjbgWYCLq+Fov5hdePJpuv/w9uk0GYppx+SYiXXQgTY2a4WNE9Y44/axO/+nykWRVfwP2Ew8t7atkxZs0YDNTO1TqPkemKrddZDlXSbvG/slVMUG1mOQzbRWdyTacliK5Y462rK7Q8UV1H0f7qR+RMl04S8VGVObQKK2TQVVowxUkiNR8rKwSkbi6Sv3N5cT84UhAnY50YozI61xe1H1HXlrOx1FtSI8aTBAvLkh+nrl58rWuK3PNvZy2N8O+9d0FDLhep1pPTa7lOZlGH4sPd4vNU7WqnH9pkUyJWRVV6sb+9Fe/mra94y0PowuqWEHi/Ls7KgKSTSzKHR0mNe/QvlBFpr70/HMAgNUF8TcfZv/2C1PSVmEf9iw/N4mKYK6U2R9d+ednIy6EkVNxEAGbZRfIbHT2jEQ6Ly7QvD1/VOW+4biJPXskWnWCC6SMT9CzPzEm75sSp602BVWvM9g8NmEzbMUL5dvYPM3tu6/7ih4eHh4etwTbHon54imShvc+8FjaloC+fkaTdvwFX2ZCZXFRSJbhIXKhe+/jP5K2PfRGyoPwmc//WdpmOK9BP1cH3zUhLlBlJtfCjkgeQztpesYPiBS1xMn4n3+RpNypVeW+lCHCtH9ciJ2RQ9TWVQiA3faOc5GKU5dFQs0y21NXkYdVnoZOIlLDe9b4/HzrG19Jt2ucmS2bUaW4io5ElVseWs5/4ap4Z7QETv3I5xTBym54WZXFLirRWPNZGmdO5XNwqTaMyqLoyOi2KhTRYIIylVp1BBsfr0u1pSG0SuIdKNF2f4nGVC6IlJvL0PkyRu6jUe6Aa9FmUk27HUbs4hh3EXOunBzPnxJz8ixl16syzjpnYKwrH1Cn6QQZ51Yma/74sVcBAOfOnk3bXBSxVe6JE+NE2A9xRsi68vZy24sLQkDOMUlbVxquy9njPMUWl0ULCnjui5GsHZdv5fJl0XDXSuBtVUTCkeimI+dwUZ/aec6C2hzpuboqk+WKh9x9RLT1Rx56FADw3MtS5OGZZynL5iIXA4k7cg92jBMZ+fa3vz1ti/g+nz0nLsfPPEO5lB64j6K8K/3iDDHNY56eFsLerd2dY+JueODAfro+OwJUV8QN0zkEZCKR+hsb5AC6FnwuFA8PD48ehX+Be3h4ePQott2EcmKJVPTZWKXizJBKHbSUypG4GnL0d2JcbAg/9ANEQOYzolYe2EeRlT/+gQ+mbZ/9s7+ga12m804tifLWaJwCAGQhKux8nbZPnRM1Eazm2FEy0QyOiTkhrYunoh0TNjckRlR6l7xpiSMl8xmVtItTulaNSsbE5KFNtIrVrW6NjUp02lSdCJ04FrW5wnU6I9W35VkiZ1eWq9wvUTUTp/5uFB2mzCSZAt0Hm6Hru0RkABCwDaWoknu5yulxe715DJw0yWTFFpFnMrKgzBlDfaR27lE++LvHyf/W8ZTNhqjegaX1FKnIuYEKrbua5KZKceIEpUi9//770rYCm0T0dARMDSUcfTetolBdcrRmXZkp2CQYKzPJwUP7AQCjO6j/utBAhs02AyqxlCNAdZlH58P92nFKo7qqCkC4fTqGIGETUXVF5qjG/axxtGhLmbhc8Yjz00IUuhql8VXqONquCEvrNlK4KEoVJIrEEZ98qwqqXuwPvfPdvEt+4Io1HHlITLAPvInqvrqyoYGi8FzBkYMHJd4j4jndf1jSzk7sJWK4wBG9/cqE4sblCpYAYibZMSppsV1yrJBNT4Fia2N2SGgru1tiNp/LzeAlcA8PD48exbZL4McX6RvyhW9LtOND+0ga2ZkVA3+RpYDxnfSFGx8RqeSug0xGWpEapjgvySc+/Rdp23MvEinkIj27AhutI5HkHHGOrhFrYo5d8zpMiHYCRfK52VSlkRotPq/60kZMaIYsbVmVK6TDlE5Gfa1daa1We/NILdsWib2/RBLFiiJC2zFJZffc+4D8ZoKkkRmOvptR0XernBdFpz9wkqON5byliKSMe95IaTovqVJpV5ZJwq+3RCKscyEFHfWZY9fGEmsaAyr3xyhXGB+fEMnm0C5y89uREzF0lV0P59nNLszK/BVLRFqXVcTrMOe/uHRGiCuHNkvvjVXRYAJHHioR0hVriNlV8OTJE+m+lSVHJMsj5opeREp8TjgkL+BIVijXyGHWmjQ5WuMUxPW6zOmFC5Ndx6ngPlh2uay15J456bk6KxpuhvvpSth1VKRild0IO8p1USIZN5ca60r7CNklMrIqQpaf146KkO3wPLjz67JsTqDvKA3GlTdrqRwkE3s5n1HCKVsTVTSBn/Mz58U1s95yeXRUgZD+A13XX1iSa0YsUZcq+2WwLp/Qkoz50vQ8n4M6nlPpsV2AqSnL+mgsbF7mbzN4CdzDw8OjR+Ff4B4eHh49im03oayyWvHXz4v6eeJ1is58z5uERLprglT1M6cpEvIdbxZTQJ5V75WWqGef+UtKF/n8q5KQqOaiwNiEEajUnU7NCVT0mDN7xEo9a7Jpo80qnlG+xU2OaNTkTRStr99Y5MQ7WbgK2ekuxEwC6iRSHSb8sn1SxWZt6pm5S5K4Km6TKlZX6m3tAiXyGlIVwEc5zWqGq8AUVNapeugqjGg703q1uVYns8s7uCrS/fdKsqfz58k8MbcokaxNR44p8itiYrrArNOIIiwHSiW+styDy7M0luOzktTIMBFV2UFmoUJFCM4ik546TW1ZkVJrUeB71lJmCkcud9V5dP7fbH6oVCQ6OM8+9eWSkHAhj6uoojmdyeLka5QIbWleVPsljpiMlc93JssRoWo95VgfN646vYrmnGGirdYU9TzkMQz2y3pqsbmtxk7qHZUsK0nNJTofKs+H2VwG/OY3vyZj6VBVnFIk8xHzumsrM4kj0l0CL/0stdlUpZ9HRxA2mtIWpxWeODWzqn85NEDm2XJZV4RyFeL18EzXX11t3o05UCaRiJNkBWb9cW4IXeENht8fRTk+aLD5TxHU14KXwD08PDx6FNsugQ+PUH6I+QX5/E1x1Njfct1JAIjb+3iLvnSjOyWK0oT0hf3uUYnG+ouvUiRVM5EvPvhLHATrv1sxS4ZWfYade5iWAlwUZYa//EZ/LjmPgyapXC1Fnbsl5OuHliUKqzQBluK1WD6+k6TFvoqSGmvdEvjO8aF0e/L8JI9JJ8+n7TMnjqdNS+ze565eVW6KVZZ2kriL6aXjVSrhVpMktue/TdXu31mScT7A46z3izTsSDsdZdtggm2JoyM1mXruNYp2m61LZGAjQ9cv7JAxD+4kiSpXoTGFKhKzyG54uaKQ4ibcfOk7V9W4I/fARfEmHaWN8dgdiVlQkYoBa4V1lVOkOU/a4HldjIHnwaVUdflmACG7M3kl9fMlWi2Zv5UFkrgbjVX+K8Szu1N5tebbdU5Jq+qXOsLR/dXkoXP36yjtw7LUms1sTqznVSRwO+T7olJE59hJIFGup86NMuBratI44XwxWup3EamJVVG2PGrr6k6qqvdOeA9UXdco5BTOTYkcTQlNHp6uudlmjVhr1W7NmK4q893vmZaKKrV8joZ6feRC0pYmJvZhq/ASuIeHh0ePYtslcCetZlSWvE6DpKcz0yJ1NasUXPGOR6jCeWFAVY/n4gff+I5k5Kuz7batssHl2I3LSRcbVQgKlTSQfkyVbSzHkptxolCgjs+RlFFQ5bycy1FbBa6ssFTmgiCaStLrH2QXynFJDF9m/8S6CrxY++nde0QynS2zS111clYdwVnplHvYPF83y2NuKXu32F3Xu4l1JeBnnHyZ8k9cWBHJZjSg+ejSYFgqWVX29suWpL5TbBOdVDk0akXWYPZKQv2xAySh5AfElTS9DywVlcuiCRTZHh6oNWavYrtd5jw7tRVxI5y5RGuy0ZC+uXJoLg+GvsdOkwtU8FCGA80cLwJIBsiIbebaZbDNdmCdT6XZpLWzotzV3G0rVdg9VUl+tk3z3FxV1e45N8iSkjid5O3sy0bZuxO7PpjL5YYxyeZFRhJ1H1erxIMUQ30P6G+sFrMLOGqxW2yno1zruHCFVdK2ZH2U57DDNvDYaXvqXrsgJi0cW0v9bDZ0bpi463itmduUj4lVmwvi00VRuq8ZtnS/OffMoC70QtsT8BK4h4eHxz94+Be4h4eHR4/imiYUY0wewDdBNQQiAJ+11v6GMeYAgE8DGALwPICft1aFQm4RKSmkibyQVMGWIlmmV0nNef44EUHvrYlKs2LJtHBxQUwMeVahOzU5R4NVRlfDMFJRcm5fl5uYcW5IcpwNulOwZnLiErbKrlctlZLWmVO0GcGZTKocEVoeEHPJIOdSaKkUmK+xi1lGuU+9aY2WVRkUQm90jPKTTCkTSqrOqd802Uzi6iVqV734KhF2XXv4xG1Wwauzki8jyHGKXuXCdomv8aKqbH8q4vkok1pe2iNFIUYnKKfNMBdZAIAcu+a1VE8sq/m5iKuwR5pIdm2KZLyKr9bls+TSqquEO5Xa6IhaTmfrqpNr9TnL5hqdB8bt1wRhh00Gq6tcs7Spc5awC5vRLn20LrKq+MDYrgk+B0VMLi+I22aHCzRYXYGeb1qtpc0qzjzhfN6w7viMGrsrtFCrKbPeGly4IE4FJ6eoHyVV4zJi20/cVW6A5tRFWyaKWM9yrhzd5kwusU4NxPPsSEajcow4clTbqlw+FX1fnLtrErsoTUVOssmxK+eRK1hh10eOul+2VZ6leIjWxa4HxVW6393S60iJshUJvAngXdbaNwJ4CMDjxpi3AvgtAL9jrT0MYAHAh7Z+WQ8PDw+Pm8VWKvJYAM7vKcP/LIB3AXCl0D8F4D8B+Nh198CRAzpRPgebJCpvgstHcmaGvvif+MyX033veicldT9zSaS/qnPOV9+ojMvkxlJAUbkBZblQQ31FpGdHNFhFMmaYUHQSniaunKSXKMKjzi5jus0dN8BS87BKAn9ljgI5FmclA+LiOQpeOnTwADZDIS8SWY4DRjIqH0jMZJb+uHdSyYTHp3deRQroorRY2lnl8b2mpLp+Lrf2WkMS37/C2slcRSTT4T00rvEDJG0PKJfIHLslBiqfRZvXShip0mQs8UZpUIscn0rP2sXrKiRmmLArnXLlTN399HlZGwusk8jkHE12iey0ZT05iVpXRHdwZHcmq0vecRk8TQLzWsznlDtegX4zP0fX1FkGM6xRhrr6OWubHS0triHhugJXXIELpdWsctGQWlXyqaxFYFU5PieNxiK1Omm/KxgoZDdC61z1lCbFkq+Ka0rn3ipXQXcjrPgMpnBStnb17fD124rET/gdZF3JO/U8pHmNVEcM1o/FMlnd4YDBisrns/tBcsaIjNzvxROcD2q3aJvXwlar0odcD3MGwFcAvA5g0UqY3iSAXZv89kljzFFjzNGNvD48PDw8PG4MW3qBW2tja+1DAHYDeAzAvRsdtslvn7LWPmqtfbSocvt6eHh4eNwcrssP3Fq7aIz5OoC3AhgwxkQshe8GcOmqP94Ew1xJu6ES8Fc5Uiwbij+1SzPpfHm/8d2X031nuD7fYlWYjPlVUoMVF4gSq+MdVqNyqrq6U73zBZVnIXA+uqKqO5/VDpsMjPYPZZUqVhXUW+ynWlD5L1xS+aERMp20FIHb5AIG9ZxcM+HoPF2xfC3aKmKyyvks+gbkmo0qqc26YEDM6l6awVSlMjXrtfwUVqXLtUwAVdlH91uqCMe5GrXNqXwP0RhV6B7fPZq2HRil7eF+mpdARXNWWS5oKCIqYlVe16zMc5RlxNXB8wURFnI89zrK8WpINsjD4ZRNq0w5ltnf1ESjzuEi+WJtAuB1pNedW2OOVO2yYiVuPQkJHDNZ3MrIvXUV6p3pJNGEJedOaSjt143Lal9od7wzP6h+RDwW2xLieWGOzGLt1uZrsqP8wGM+rhVoAtflxdFFQLiJn6VA3QOXMjbRpg42cyUq/bIjkJ01Qx/vTGDaapM4/2xlMnNmo9TUov272cwDTbA6M4x6H7Q5rfPQ3VQ8Ytf+Pem+BtfTfP01iV0ptNlSLUHm18Q1JXBjzKgxZoC3CwB+FMAxAF8D8AE+7AkAX9j6ZT08PDw8bhZbkcDHAXzKUEKBAMBnrLVfMsa8CuDTxpj/DOAFAB+/kQ40WKrMqU9JkyWgTChSaIc/hC5BfVAQKe0sk5eBIlk6LB11FAHZ4IxrVY6E1ESNk4pKWZHSCkxsBkpqcARhoUjX1zkprnAmuUS5C0VMYAxWhGTcOURax86dRNYtVkVSWebMfatLEgU4wIn9Z6/oyMoRaLRVlfUwS2MfHJVrtss0l522yvyWuL9McCoJ3A1ZR+Sl0plm6xzRxtn62ioHSbOf+n3XgJAyg0MUPVmuyNIrF+m+5Zggbqh8Iy12O7RKeg6d+6fuB29nWJPSboSuWIEmxOxVWNoGu95F2n3UuaZpV0QeuyvsoNfTWsmaO0Bd1ZGSPPfOjS9WkY1tnodQaV5tzqcRK3fXUpM0Fyd561w1zTpL7xuUPks2iKh1/Yj0fHO/56cl/06bI0L1LVgHPXTOmRJk5ZoZlw007qpAwT/luVKnsy6Dn9IA86xhDFaE+HYl1FwBEj2nIbt85pSG6/KcdEWf8n1xkakryyqPCS/PJJI5WuJUg9GI9GPfESIqBzm6+uJrp9J9s6co42qk+pa/Sl6ZzbAVL5SXATy8QftpkD3cw8PDw2Mb4CMxPTw8PHoU257Myql4OZX0p+iIjLaojs7NM2EvZJ1gJ2F1q9NSpFPsUkpqIoq2kzRlpXy/FubJdDGvrlnhQgD9Ksqxwr7jeZB5xVWXBoCIVbxQ1WpscvIjVxBAH9epca3Bmkr6szjHYxf2Nc8Rf42rRA+GSv0aGCbzTrmk/MCbbFJSJpRO7HzDne+vSszF3/agKz0mmwVUMqaIVeIimyz6+lSEICfNL+eEjC6xb3g2J+pnizdX2W+9rghZR7TmlbqaDZ3PtKjBwRrzhL7vLSapsllFOmU2n0sXXRsoM0XGme60+YP75maoq6h4Gpmnkj3F64lkF4nsCju0WnLf62w6iesqYpJJzJIyMxX6SUXv8DjbDTlHsIGNI/WH14R2WjSeNkoqRqLKtU2Xl8Ws5yxQes2sRdhRc8x1JxMVgWtB/Q2hUujytkStKgLS2K6/AJBwsrpaJInvJJrapYNW883R0o229M2tddPlS552ks+kQj35+pqgrnBq49EjEqsR8Lvq+LPfoWvOiAk05PunC3NsZNK6FrwE7uHh4dGjMPYG3vo3iomJCfvkk0/etut5eHh4/EPARz/60eestY+ubfcSuIeHh0ePwr/APTw8PHoU/gXu4eHh0aPwL3APDw+PHsVtJTGNMVcAVAHMXuvYOxwj6O0x9Hr/gd4fQ6/3H+j9MfRS//dZa0fXNt7WFzgAGGOObsSm9hJ6fQy93n+g98fQ6/0Hen8Mvd5/wJtQPDw8PHoW/gXu4eHh0aPYjhf4U9twzVuNXh9Dr/cf6P0x9Hr/gd4fQ6/3//bbwD08PDw8bg28CcXDw8OjR3FbX+DGmMeNMceNMaeMMR+5nde+ERhj9hhjvmaMOWaMecUY80vcPmSM+Yox5iT/Hdzuvl4NXJT6BWPMl/j/B4wx3+H+/6kxJnutc2wnjDEDxpjPGmNe43vxth68B/+e19D3jTF/YozJ38n3wRjzCWPMjDHm+6ptwzk3hP/Oz/XLxphHtq/ngk3G8F94Hb1sjPkzV22M9/0aj+G4Meafbk+vrw+37QXOFX1+D8B7ANwH4GeNMffdruvfIDoAfsVaey+oDugvcp8/AuBpa+1hAE/z/+9k/BKoDJ7DbwH4He7/AoAPbUuvto7fBfCX1tp7ALwRNJaeuQfGmF0A/h2AR621D4Bq1XwQd/Z9+CSAx9e0bTbn7wFwmP89CeBjt6mP18InsX4MXwHwgLX2DQBOAPg1AODn+oMA7uff/A/TlV/2zsTtlMAfA3DKWnvaWtsC8GkA77+N179uWGunrLXP8/YK6MWxC9TvT/FhnwLwU9vTw2vDGLMbwI8D+H3+vwHwLgCf5UPu9P5XALwDXLLPWtuy1i6ih+4BIwJQMMZEAIoApnAH3wdr7TcBzK9p3mzO3w/gDy3hGVDB8/Hb09PNsdEYrLV/ZSVJ+zOQEsLvB/Bpa23TWnsGwCn0QMWx2/kC3wXggvr/JLf1BIwx+0Gl5b4DYMxaOwXQSx7Aju3r2TXx3wD8BwAuq/0wgEW1iO/0+3AQwBUAf8BmoN83xpTQQ/fAWnsRwH8FcB704l4C8Bx66z4Am895rz7b/xrA/+XtnhzD7XyBb1SxsydcYIwxZQCfA/DL1trlax1/p8AY8xMAZqy1z+nmDQ69k+9DBOARAB+z1j4MSsVwx5pLNgLbit8P4ACACQAlkNlhLe7k+3A19NqagjHm10Em0j92TRscdkePAbi9L/BJAHvU/3cDuHQbr39DMMZkQC/vP7bWfp6bp52KyH9nNvv9NuMHAbzPGHMWZLJ6F0giH2BVHrjz78MkgElr7Xf4/58FvdB75R4AwI8COGOtvWKtbQP4PIAfQG/dB2DzOe+pZ9sY8wSAnwDwc1b8qHtqDA638wX+LIDDzLxnQYTBF2/j9a8bbC/+OIBj1trfVru+COAJ3n4CwBdud9+2AmvtUPp/igAAAUpJREFUr1lrd1tr94Pm+6vW2p8D8DUAH+DD7tj+A4C19jKAC8aYu7np3QBeRY/cA8Z5AG81xhR5Tbkx9Mx9YGw2518E8AvsjfJWAEvO1HKnwRjzOIBfBfA+a21N7foigA8aY3LGmAMgQva729HH64K19rb9A/BeEPP7OoBfv53XvsH+vh2kRr0M4EX+916QHflpACf579B293ULY3kngC/x9kHQ4jwF4H8DyG13/67R94cAHOX78OcABnvtHgD4KIDXAHwfwB8ByN3J9wHAn4Ds9W2QdPqhzeYcZH74PX6uvwfytrlTx3AKZOt2z/P/VMf/Oo/hOID3bHf/t/LPR2J6eHh49Ch8JKaHh4dHj8K/wD08PDx6FP4F7uHh4dGj8C9wDw8Pjx6Ff4F7eHh49Cj8C9zDw8OjR+Ff4B4eHh49Cv8C9/Dw8OhR/H86g/sGL68EWQAAAABJRU5ErkJggg==\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "GroundTruth:    cat  ship  ship plane\n"
     ]
    }
   ],
   "source": [
    "dataiter = iter(testloader)\n",
    "images, labels = dataiter.next()\n",
    "\n",
    "# print images\n",
    "imshow(torchvision.utils.make_grid(images))\n",
    "print('GroundTruth: ', ' '.join('%5s' % classes[labels[j]] for j in range(4)))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [],
   "source": [
    "outputs = vgg19(images.to(device))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Predicted:  truck  bird truck truck\n"
     ]
    }
   ],
   "source": [
    "_, predicted = torch.max(outputs, 1)\n",
    "\n",
    "print('Predicted: ', ' '.join('%5s' % classes[predicted[j]]\n",
    "                              for j in range(4)))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. ResNet 34 - CIFAR10\n",
    "https://github.com/deeplearningzerotoall/PyTorch/blob/master/lab-10_6_2_Advance-CNN(ResNet_cifar10).ipynb\n",
    "- 위 링크의 코드 그대로 사용\n",
    "- ResNet34 : block은 BasicBlock 사용하고, layer는 ResNet50처럼 [3, 4, 6, 3] 사용\n",
    "- epoch 2번까지"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "metadata": {},
   "outputs": [],
   "source": [
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.optim as optim\n",
    "import torchvision\n",
    "import torchvision.transforms as transforms"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 38,
   "metadata": {},
   "outputs": [],
   "source": [
    "import warnings\n",
    "warnings.filterwarnings(action='ignore')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Setting up a new session...\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception in user code:\n",
      "------------------------------------------------------------\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 157, in _new_conn\n",
      "    (self._dns_host, self.port), self.timeout, **extra_kw\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\connection.py\", line 84, in create_connection\n",
      "    raise err\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\connection.py\", line 74, in create_connection\n",
      "    sock.connect(sa)\n",
      "ConnectionRefusedError: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 672, in urlopen\n",
      "    chunked=chunked,\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 387, in _make_request\n",
      "    conn.request(method, url, **httplib_request_kw)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1252, in request\n",
      "    self._send_request(method, url, body, headers, encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1298, in _send_request\n",
      "    self.endheaders(body, encode_chunked=encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1247, in endheaders\n",
      "    self._send_output(message_body, encode_chunked=encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1026, in _send_output\n",
      "    self.send(msg)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 966, in send\n",
      "    self.connect()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 184, in connect\n",
      "    conn = self._new_conn()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 169, in _new_conn\n",
      "    self, \"Failed to establish a new connection: %s\" % e\n",
      "urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000205830F4E88>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\adapters.py\", line 449, in send\n",
      "    timeout=timeout\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 720, in urlopen\n",
      "    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\retry.py\", line 436, in increment\n",
      "    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n",
      "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /env/main (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000205830F4E88>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다'))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\visdom\\__init__.py\", line 711, in _send\n",
      "    data=json.dumps(msg),\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\visdom\\__init__.py\", line 677, in _handle_post\n",
      "    r = self.session.post(url, data=data)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 581, in post\n",
      "    return self.request('POST', url, data=data, json=json, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 533, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 646, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\adapters.py\", line 516, in send\n",
      "    raise ConnectionError(e, request=request)\n",
      "requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /env/main (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000205830F4E88>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다'))\n",
      "[WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다\n",
      "Visdom python client failed to establish socket to get messages from the server. This feature is optional and can be disabled by initializing Visdom with `use_incoming_socket=False`, which will prevent waiting for this request to timeout.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception in user code:\n",
      "------------------------------------------------------------\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 157, in _new_conn\n",
      "    (self._dns_host, self.port), self.timeout, **extra_kw\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\connection.py\", line 84, in create_connection\n",
      "    raise err\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\connection.py\", line 74, in create_connection\n",
      "    sock.connect(sa)\n",
      "ConnectionRefusedError: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 672, in urlopen\n",
      "    chunked=chunked,\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 387, in _make_request\n",
      "    conn.request(method, url, **httplib_request_kw)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1252, in request\n",
      "    self._send_request(method, url, body, headers, encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1298, in _send_request\n",
      "    self.endheaders(body, encode_chunked=encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1247, in endheaders\n",
      "    self._send_output(message_body, encode_chunked=encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1026, in _send_output\n",
      "    self.send(msg)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 966, in send\n",
      "    self.connect()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 184, in connect\n",
      "    conn = self._new_conn()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 169, in _new_conn\n",
      "    self, \"Failed to establish a new connection: %s\" % e\n",
      "urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000205830F7E48>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\adapters.py\", line 449, in send\n",
      "    timeout=timeout\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 720, in urlopen\n",
      "    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\retry.py\", line 436, in increment\n",
      "    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n",
      "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /close (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000205830F7E48>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다'))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\visdom\\__init__.py\", line 711, in _send\n",
      "    data=json.dumps(msg),\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\visdom\\__init__.py\", line 677, in _handle_post\n",
      "    r = self.session.post(url, data=data)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 581, in post\n",
      "    return self.request('POST', url, data=data, json=json, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 533, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 646, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\adapters.py\", line 516, in send\n",
      "    raise ConnectionError(e, request=request)\n",
      "requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /close (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000205830F7E48>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다'))\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "False"
      ]
     },
     "execution_count": 39,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import visdom\n",
    "\n",
    "vis = visdom.Visdom()\n",
    "vis.close(env=\"main\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "metadata": {},
   "outputs": [],
   "source": [
    "#define value_tracker\n",
    "def value_tracker(value_plot, value, num):\n",
    "    '''num, loss_value, are Tensor'''\n",
    "    vis.line(X=num,\n",
    "             Y=value,\n",
    "             win = value_plot,\n",
    "             update='append'\n",
    "             )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 41,
   "metadata": {},
   "outputs": [],
   "source": [
    "device = 'cuda' if torch.cuda.is_available() else 'cpu'\n",
    "\n",
    "torch.manual_seed(777)\n",
    "if device =='cuda':\n",
    "    torch.cuda.manual_seed_all(777)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Files already downloaded and verified\n",
      "(50000, 32, 32, 3)\n",
      "[125.30691805 122.95039414 113.86538318]\n",
      "[62.99321928 62.08870764 66.70489964]\n",
      "[0.49139968 0.48215841 0.44653091]\n",
      "[0.24703223 0.24348513 0.26158784]\n"
     ]
    }
   ],
   "source": [
    "transform = transforms.Compose([\n",
    "    transforms.ToTensor()\n",
    "])\n",
    "\n",
    "trainset = torchvision.datasets.CIFAR10(root='./cifar10', train=True, download=True, transform=transform)\n",
    "\n",
    "print(trainset.data.shape)\n",
    "\n",
    "train_data_mean = trainset.data.mean( axis=(0,1,2) )\n",
    "train_data_std = trainset.data.std( axis=(0,1,2) )\n",
    "\n",
    "print(train_data_mean)\n",
    "print(train_data_std)\n",
    "\n",
    "train_data_mean = train_data_mean / 255 #train 데이터셋의 mean과 std구한 후, 255로 나눠줌\n",
    "train_data_std = train_data_std / 255\n",
    "\n",
    "print(train_data_mean)\n",
    "print(train_data_std)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Files already downloaded and verified\n",
      "Files already downloaded and verified\n"
     ]
    }
   ],
   "source": [
    "transform_train = transforms.Compose([\n",
    "    transforms.RandomCrop(32, padding=4),\n",
    "    transforms.ToTensor(),\n",
    "    transforms.Normalize(train_data_mean, train_data_std)])\n",
    "\n",
    "transform_test = transforms.Compose([\n",
    "    transforms.ToTensor(),\n",
    "    transforms.Normalize(train_data_mean, train_data_std)\n",
    "])\n",
    "\n",
    "trainset = torchvision.datasets.CIFAR10(root='./cifar10', train=True,\n",
    "                                        download=True, transform=transform_train)\n",
    "trainloader = torch.utils.data.DataLoader(trainset, batch_size=256,\n",
    "                                          shuffle=True, num_workers=0)\n",
    "\n",
    "testset = torchvision.datasets.CIFAR10(root='./cifar10', train=False,\n",
    "                                       download=True, transform=transform_test)\n",
    "\n",
    "testloader = torch.utils.data.DataLoader(testset, batch_size=256,\n",
    "                                         shuffle=False, num_workers=0)\n",
    "\n",
    "classes = ('plane', 'car', 'bird', 'cat','deer', 'dog', 'frog', 'horse', 'ship', 'truck')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### make ResNet50 using resnet"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 44,
   "metadata": {},
   "outputs": [],
   "source": [
    "import torchvision.models.resnet as resnet"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 45,
   "metadata": {},
   "outputs": [],
   "source": [
    "conv1x1=resnet.conv1x1\n",
    "Bottleneck = resnet.Bottleneck\n",
    "BasicBlock= resnet.BasicBlock"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 46,
   "metadata": {},
   "outputs": [],
   "source": [
    "class ResNet(nn.Module):\n",
    "\n",
    "    def __init__(self, block, layers, num_classes=1000, zero_init_residual=False):\n",
    "        super(ResNet, self).__init__()\n",
    "        self.inplanes = 16\n",
    "        self.conv1 = nn.Conv2d(3, 16, kernel_size=3, stride=1, padding=1,\n",
    "                               bias=False)\n",
    "        self.bn1 = nn.BatchNorm2d(16)\n",
    "        self.relu = nn.ReLU(inplace=True)\n",
    "        #self.maxpool = nn.MaxPool2d(kernel_size=3, stride=2, padding=1)\n",
    "        \n",
    "        self.layer1 = self._make_layer(block, 16, layers[0], stride=1)\n",
    "        self.layer2 = self._make_layer(block, 32, layers[1], stride=1)\n",
    "        self.layer3 = self._make_layer(block, 64, layers[2], stride=2)\n",
    "        self.layer4 = self._make_layer(block, 128, layers[3], stride=2)\n",
    "        \n",
    "        self.avgpool = nn.AdaptiveAvgPool2d((1, 1))\n",
    "        self.fc = nn.Linear(128 * block.expansion, num_classes)\n",
    "\n",
    "        for m in self.modules():\n",
    "            if isinstance(m, nn.Conv2d):\n",
    "                nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')\n",
    "            elif isinstance(m, nn.BatchNorm2d):\n",
    "                nn.init.constant_(m.weight, 1)\n",
    "                nn.init.constant_(m.bias, 0)\n",
    "\n",
    "        # Zero-initialize the last BN in each residual branch,\n",
    "        # so that the residual branch starts with zeros, and each residual block behaves like an identity.\n",
    "        # This improves the model by 0.2~0.3% according to https://arxiv.org/abs/1706.02677\n",
    "        if zero_init_residual:\n",
    "            for m in self.modules():\n",
    "                if isinstance(m, Bottleneck):\n",
    "                    nn.init.constant_(m.bn3.weight, 0)\n",
    "                elif isinstance(m, BasicBlock):\n",
    "                    nn.init.constant_(m.bn2.weight, 0)\n",
    "\n",
    "    def _make_layer(self, block, planes, blocks, stride=1):\n",
    "        downsample = None\n",
    "        if stride != 1 or self.inplanes != planes * block.expansion:\n",
    "            downsample = nn.Sequential(\n",
    "                conv1x1(self.inplanes, planes * block.expansion, stride),\n",
    "                nn.BatchNorm2d(planes * block.expansion),\n",
    "            )\n",
    "\n",
    "        layers = []\n",
    "        layers.append(block(self.inplanes, planes, stride, downsample))\n",
    "        self.inplanes = planes * block.expansion\n",
    "        for _ in range(1, blocks):\n",
    "            layers.append(block(self.inplanes, planes))\n",
    "\n",
    "        return nn.Sequential(*layers)\n",
    "\n",
    "    def forward(self, x):\n",
    "        x = self.conv1(x)\n",
    "        #x.shape =[1, 16, 32,32]\n",
    "        x = self.bn1(x)\n",
    "        x = self.relu(x)\n",
    "        #x = self.maxpool(x)\n",
    "\n",
    "        x = self.layer1(x)\n",
    "        #x.shape =[1, 128, 32,32]\n",
    "        x = self.layer2(x)\n",
    "        #x.shape =[1, 256, 32,32]\n",
    "        x = self.layer3(x)\n",
    "        #x.shape =[1, 512, 16,16]\n",
    "        x = self.layer4(x)\n",
    "        #x.shape =[1, 1024, 8,8]\n",
    "        \n",
    "        x = self.avgpool(x)\n",
    "        x = x.view(x.size(0), -1)\n",
    "        x = self.fc(x)\n",
    "\n",
    "        return x"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 47,
   "metadata": {},
   "outputs": [],
   "source": [
    "resnet34 = ResNet(resnet.BasicBlock, [3, 4, 6, 3], 10, True).to(device) \n",
    "# block은 BasicBlock 사용하고, layer는 ResNet50처럼 [3, 4, 6, 3] 사용\n",
    "# 2*(3+4+6+3) +(conv1) +1(fc) = 32+2 = 34"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 48,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "tensor([[-0.0196, -0.0132, -0.0700,  0.0751,  0.0726, -0.0021,  0.0627, -0.0392,\n",
      "          0.0873, -0.0145]], grad_fn=<AddmmBackward>)\n"
     ]
    }
   ],
   "source": [
    "a=torch.Tensor(1,3,32,32).to(device)\n",
    "out = resnet34(a)\n",
    "print(out)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 52,
   "metadata": {},
   "outputs": [],
   "source": [
    "criterion = nn.CrossEntropyLoss().to(device)\n",
    "optimizer = torch.optim.SGD(resnet34.parameters(), lr = 0.1, momentum = 0.9, weight_decay=5e-4)\n",
    "#lr_sche = optim.lr_scheduler.StepLR(optimizer, step_size=10, gamma=0.5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "196\n",
      "Exception in user code:\n",
      "------------------------------------------------------------\n",
      "[1,    30] loss: 1.128\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 157, in _new_conn\n",
      "    (self._dns_host, self.port), self.timeout, **extra_kw\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\connection.py\", line 84, in create_connection\n",
      "    raise err\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\connection.py\", line 74, in create_connection\n",
      "    sock.connect(sa)\n",
      "ConnectionRefusedError: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 672, in urlopen\n",
      "    chunked=chunked,\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 387, in _make_request\n",
      "    conn.request(method, url, **httplib_request_kw)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1252, in request\n",
      "    self._send_request(method, url, body, headers, encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1298, in _send_request\n",
      "    self.endheaders(body, encode_chunked=encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1247, in endheaders\n",
      "    self._send_output(message_body, encode_chunked=encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1026, in _send_output\n",
      "    self.send(msg)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 966, in send\n",
      "    self.connect()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 184, in connect\n",
      "    conn = self._new_conn()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 169, in _new_conn\n",
      "    self, \"Failed to establish a new connection: %s\" % e\n",
      "urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000205830F7308>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\adapters.py\", line 449, in send\n",
      "    timeout=timeout\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 720, in urlopen\n",
      "    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\retry.py\", line 436, in increment\n",
      "    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n",
      "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /update (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000205830F7308>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다'))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\visdom\\__init__.py\", line 711, in _send\n",
      "    data=json.dumps(msg),\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\visdom\\__init__.py\", line 677, in _handle_post\n",
      "    r = self.session.post(url, data=data)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 581, in post\n",
      "    return self.request('POST', url, data=data, json=json, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 533, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 646, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\adapters.py\", line 516, in send\n",
      "    raise ConnectionError(e, request=request)\n",
      "requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /update (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000205830F7308>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다'))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception in user code:\n",
      "------------------------------------------------------------\n",
      "[1,    60] loss: 1.064\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 157, in _new_conn\n",
      "    (self._dns_host, self.port), self.timeout, **extra_kw\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\connection.py\", line 84, in create_connection\n",
      "    raise err\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\connection.py\", line 74, in create_connection\n",
      "    sock.connect(sa)\n",
      "ConnectionRefusedError: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 672, in urlopen\n",
      "    chunked=chunked,\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 387, in _make_request\n",
      "    conn.request(method, url, **httplib_request_kw)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1252, in request\n",
      "    self._send_request(method, url, body, headers, encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1298, in _send_request\n",
      "    self.endheaders(body, encode_chunked=encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1247, in endheaders\n",
      "    self._send_output(message_body, encode_chunked=encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1026, in _send_output\n",
      "    self.send(msg)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 966, in send\n",
      "    self.connect()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 184, in connect\n",
      "    conn = self._new_conn()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 169, in _new_conn\n",
      "    self, \"Failed to establish a new connection: %s\" % e\n",
      "urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000205830D75C8>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\adapters.py\", line 449, in send\n",
      "    timeout=timeout\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 720, in urlopen\n",
      "    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\retry.py\", line 436, in increment\n",
      "    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n",
      "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /update (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000205830D75C8>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다'))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\visdom\\__init__.py\", line 711, in _send\n",
      "    data=json.dumps(msg),\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\visdom\\__init__.py\", line 677, in _handle_post\n",
      "    r = self.session.post(url, data=data)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 581, in post\n",
      "    return self.request('POST', url, data=data, json=json, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 533, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 646, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\adapters.py\", line 516, in send\n",
      "    raise ConnectionError(e, request=request)\n",
      "requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /update (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000205830D75C8>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다'))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception in user code:\n",
      "------------------------------------------------------------\n",
      "[1,    90] loss: 1.057\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 157, in _new_conn\n",
      "    (self._dns_host, self.port), self.timeout, **extra_kw\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\connection.py\", line 84, in create_connection\n",
      "    raise err\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\connection.py\", line 74, in create_connection\n",
      "    sock.connect(sa)\n",
      "ConnectionRefusedError: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 672, in urlopen\n",
      "    chunked=chunked,\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 387, in _make_request\n",
      "    conn.request(method, url, **httplib_request_kw)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1252, in request\n",
      "    self._send_request(method, url, body, headers, encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1298, in _send_request\n",
      "    self.endheaders(body, encode_chunked=encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1247, in endheaders\n",
      "    self._send_output(message_body, encode_chunked=encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1026, in _send_output\n",
      "    self.send(msg)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 966, in send\n",
      "    self.connect()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 184, in connect\n",
      "    conn = self._new_conn()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 169, in _new_conn\n",
      "    self, \"Failed to establish a new connection: %s\" % e\n",
      "urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000205830D7F48>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\adapters.py\", line 449, in send\n",
      "    timeout=timeout\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 720, in urlopen\n",
      "    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\retry.py\", line 436, in increment\n",
      "    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n",
      "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /update (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000205830D7F48>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다'))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\visdom\\__init__.py\", line 711, in _send\n",
      "    data=json.dumps(msg),\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\visdom\\__init__.py\", line 677, in _handle_post\n",
      "    r = self.session.post(url, data=data)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 581, in post\n",
      "    return self.request('POST', url, data=data, json=json, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 533, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 646, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\adapters.py\", line 516, in send\n",
      "    raise ConnectionError(e, request=request)\n",
      "requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /update (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000205830D7F48>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다'))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception in user code:\n",
      "------------------------------------------------------------\n",
      "[1,   120] loss: 1.055\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 157, in _new_conn\n",
      "    (self._dns_host, self.port), self.timeout, **extra_kw\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\connection.py\", line 84, in create_connection\n",
      "    raise err\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\connection.py\", line 74, in create_connection\n",
      "    sock.connect(sa)\n",
      "ConnectionRefusedError: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 672, in urlopen\n",
      "    chunked=chunked,\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 387, in _make_request\n",
      "    conn.request(method, url, **httplib_request_kw)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1252, in request\n",
      "    self._send_request(method, url, body, headers, encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1298, in _send_request\n",
      "    self.endheaders(body, encode_chunked=encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1247, in endheaders\n",
      "    self._send_output(message_body, encode_chunked=encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1026, in _send_output\n",
      "    self.send(msg)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 966, in send\n",
      "    self.connect()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 184, in connect\n",
      "    conn = self._new_conn()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 169, in _new_conn\n",
      "    self, \"Failed to establish a new connection: %s\" % e\n",
      "urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000205830F7B88>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\adapters.py\", line 449, in send\n",
      "    timeout=timeout\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 720, in urlopen\n",
      "    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\retry.py\", line 436, in increment\n",
      "    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n",
      "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /update (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000205830F7B88>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다'))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\visdom\\__init__.py\", line 711, in _send\n",
      "    data=json.dumps(msg),\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\visdom\\__init__.py\", line 677, in _handle_post\n",
      "    r = self.session.post(url, data=data)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 581, in post\n",
      "    return self.request('POST', url, data=data, json=json, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 533, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 646, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\adapters.py\", line 516, in send\n",
      "    raise ConnectionError(e, request=request)\n",
      "requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /update (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000205830F7B88>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다'))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception in user code:\n",
      "------------------------------------------------------------\n",
      "[1,   150] loss: 1.030\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 157, in _new_conn\n",
      "    (self._dns_host, self.port), self.timeout, **extra_kw\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\connection.py\", line 84, in create_connection\n",
      "    raise err\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\connection.py\", line 74, in create_connection\n",
      "    sock.connect(sa)\n",
      "ConnectionRefusedError: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 672, in urlopen\n",
      "    chunked=chunked,\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 387, in _make_request\n",
      "    conn.request(method, url, **httplib_request_kw)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1252, in request\n",
      "    self._send_request(method, url, body, headers, encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1298, in _send_request\n",
      "    self.endheaders(body, encode_chunked=encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1247, in endheaders\n",
      "    self._send_output(message_body, encode_chunked=encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1026, in _send_output\n",
      "    self.send(msg)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 966, in send\n",
      "    self.connect()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 184, in connect\n",
      "    conn = self._new_conn()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 169, in _new_conn\n",
      "    self, \"Failed to establish a new connection: %s\" % e\n",
      "urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000205850AEF48>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\adapters.py\", line 449, in send\n",
      "    timeout=timeout\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 720, in urlopen\n",
      "    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\retry.py\", line 436, in increment\n",
      "    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n",
      "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /update (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000205850AEF48>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다'))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\visdom\\__init__.py\", line 711, in _send\n",
      "    data=json.dumps(msg),\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\visdom\\__init__.py\", line 677, in _handle_post\n",
      "    r = self.session.post(url, data=data)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 581, in post\n",
      "    return self.request('POST', url, data=data, json=json, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 533, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 646, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\adapters.py\", line 516, in send\n",
      "    raise ConnectionError(e, request=request)\n",
      "requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /update (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000205850AEF48>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다'))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception in user code:\n",
      "------------------------------------------------------------\n",
      "[1,   180] loss: 0.959\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 157, in _new_conn\n",
      "    (self._dns_host, self.port), self.timeout, **extra_kw\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\connection.py\", line 84, in create_connection\n",
      "    raise err\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\connection.py\", line 74, in create_connection\n",
      "    sock.connect(sa)\n",
      "ConnectionRefusedError: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 672, in urlopen\n",
      "    chunked=chunked,\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 387, in _make_request\n",
      "    conn.request(method, url, **httplib_request_kw)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1252, in request\n",
      "    self._send_request(method, url, body, headers, encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1298, in _send_request\n",
      "    self.endheaders(body, encode_chunked=encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1247, in endheaders\n",
      "    self._send_output(message_body, encode_chunked=encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1026, in _send_output\n",
      "    self.send(msg)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 966, in send\n",
      "    self.connect()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 184, in connect\n",
      "    conn = self._new_conn()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 169, in _new_conn\n",
      "    self, \"Failed to establish a new connection: %s\" % e\n",
      "urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000020583121AC8>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\adapters.py\", line 449, in send\n",
      "    timeout=timeout\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 720, in urlopen\n",
      "    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\retry.py\", line 436, in increment\n",
      "    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n",
      "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /update (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020583121AC8>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다'))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\visdom\\__init__.py\", line 711, in _send\n",
      "    data=json.dumps(msg),\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\visdom\\__init__.py\", line 677, in _handle_post\n",
      "    r = self.session.post(url, data=data)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 581, in post\n",
      "    return self.request('POST', url, data=data, json=json, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 533, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 646, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\adapters.py\", line 516, in send\n",
      "    raise ConnectionError(e, request=request)\n",
      "requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /update (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020583121AC8>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다'))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception in user code:\n",
      "------------------------------------------------------------\n",
      "[2,    30] loss: 0.960\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 157, in _new_conn\n",
      "    (self._dns_host, self.port), self.timeout, **extra_kw\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\connection.py\", line 84, in create_connection\n",
      "    raise err\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\connection.py\", line 74, in create_connection\n",
      "    sock.connect(sa)\n",
      "ConnectionRefusedError: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 672, in urlopen\n",
      "    chunked=chunked,\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 387, in _make_request\n",
      "    conn.request(method, url, **httplib_request_kw)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1252, in request\n",
      "    self._send_request(method, url, body, headers, encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1298, in _send_request\n",
      "    self.endheaders(body, encode_chunked=encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1247, in endheaders\n",
      "    self._send_output(message_body, encode_chunked=encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1026, in _send_output\n",
      "    self.send(msg)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 966, in send\n",
      "    self.connect()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 184, in connect\n",
      "    conn = self._new_conn()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 169, in _new_conn\n",
      "    self, \"Failed to establish a new connection: %s\" % e\n",
      "urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000205830F7208>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\adapters.py\", line 449, in send\n",
      "    timeout=timeout\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 720, in urlopen\n",
      "    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\retry.py\", line 436, in increment\n",
      "    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n",
      "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /update (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000205830F7208>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다'))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\visdom\\__init__.py\", line 711, in _send\n",
      "    data=json.dumps(msg),\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\visdom\\__init__.py\", line 677, in _handle_post\n",
      "    r = self.session.post(url, data=data)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 581, in post\n",
      "    return self.request('POST', url, data=data, json=json, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 533, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 646, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\adapters.py\", line 516, in send\n",
      "    raise ConnectionError(e, request=request)\n",
      "requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /update (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000205830F7208>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다'))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception in user code:\n",
      "------------------------------------------------------------\n",
      "[2,    60] loss: 0.926\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 157, in _new_conn\n",
      "    (self._dns_host, self.port), self.timeout, **extra_kw\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\connection.py\", line 84, in create_connection\n",
      "    raise err\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\connection.py\", line 74, in create_connection\n",
      "    sock.connect(sa)\n",
      "ConnectionRefusedError: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 672, in urlopen\n",
      "    chunked=chunked,\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 387, in _make_request\n",
      "    conn.request(method, url, **httplib_request_kw)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1252, in request\n",
      "    self._send_request(method, url, body, headers, encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1298, in _send_request\n",
      "    self.endheaders(body, encode_chunked=encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1247, in endheaders\n",
      "    self._send_output(message_body, encode_chunked=encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1026, in _send_output\n",
      "    self.send(msg)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 966, in send\n",
      "    self.connect()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 184, in connect\n",
      "    conn = self._new_conn()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 169, in _new_conn\n",
      "    self, \"Failed to establish a new connection: %s\" % e\n",
      "urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000205830D7888>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\adapters.py\", line 449, in send\n",
      "    timeout=timeout\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 720, in urlopen\n",
      "    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\retry.py\", line 436, in increment\n",
      "    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n",
      "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /update (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000205830D7888>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다'))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\visdom\\__init__.py\", line 711, in _send\n",
      "    data=json.dumps(msg),\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\visdom\\__init__.py\", line 677, in _handle_post\n",
      "    r = self.session.post(url, data=data)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 581, in post\n",
      "    return self.request('POST', url, data=data, json=json, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 533, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 646, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\adapters.py\", line 516, in send\n",
      "    raise ConnectionError(e, request=request)\n",
      "requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /update (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000205830D7888>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다'))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception in user code:\n",
      "------------------------------------------------------------\n",
      "[2,    90] loss: 0.912\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 157, in _new_conn\n",
      "    (self._dns_host, self.port), self.timeout, **extra_kw\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\connection.py\", line 84, in create_connection\n",
      "    raise err\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\connection.py\", line 74, in create_connection\n",
      "    sock.connect(sa)\n",
      "ConnectionRefusedError: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 672, in urlopen\n",
      "    chunked=chunked,\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 387, in _make_request\n",
      "    conn.request(method, url, **httplib_request_kw)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1252, in request\n",
      "    self._send_request(method, url, body, headers, encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1298, in _send_request\n",
      "    self.endheaders(body, encode_chunked=encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1247, in endheaders\n",
      "    self._send_output(message_body, encode_chunked=encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1026, in _send_output\n",
      "    self.send(msg)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 966, in send\n",
      "    self.connect()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 184, in connect\n",
      "    conn = self._new_conn()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 169, in _new_conn\n",
      "    self, \"Failed to establish a new connection: %s\" % e\n",
      "urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000205830D7948>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\adapters.py\", line 449, in send\n",
      "    timeout=timeout\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 720, in urlopen\n",
      "    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\retry.py\", line 436, in increment\n",
      "    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n",
      "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /update (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000205830D7948>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다'))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\visdom\\__init__.py\", line 711, in _send\n",
      "    data=json.dumps(msg),\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\visdom\\__init__.py\", line 677, in _handle_post\n",
      "    r = self.session.post(url, data=data)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 581, in post\n",
      "    return self.request('POST', url, data=data, json=json, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 533, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 646, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\adapters.py\", line 516, in send\n",
      "    raise ConnectionError(e, request=request)\n",
      "requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /update (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000205830D7948>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다'))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception in user code:\n",
      "------------------------------------------------------------\n",
      "[2,   120] loss: 0.902\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 157, in _new_conn\n",
      "    (self._dns_host, self.port), self.timeout, **extra_kw\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\connection.py\", line 84, in create_connection\n",
      "    raise err\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\connection.py\", line 74, in create_connection\n",
      "    sock.connect(sa)\n",
      "ConnectionRefusedError: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 672, in urlopen\n",
      "    chunked=chunked,\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 387, in _make_request\n",
      "    conn.request(method, url, **httplib_request_kw)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1252, in request\n",
      "    self._send_request(method, url, body, headers, encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1298, in _send_request\n",
      "    self.endheaders(body, encode_chunked=encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1247, in endheaders\n",
      "    self._send_output(message_body, encode_chunked=encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1026, in _send_output\n",
      "    self.send(msg)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 966, in send\n",
      "    self.connect()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 184, in connect\n",
      "    conn = self._new_conn()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 169, in _new_conn\n",
      "    self, \"Failed to establish a new connection: %s\" % e\n",
      "urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000205850AEC08>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\adapters.py\", line 449, in send\n",
      "    timeout=timeout\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 720, in urlopen\n",
      "    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\retry.py\", line 436, in increment\n",
      "    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n",
      "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /update (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000205850AEC08>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다'))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\visdom\\__init__.py\", line 711, in _send\n",
      "    data=json.dumps(msg),\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\visdom\\__init__.py\", line 677, in _handle_post\n",
      "    r = self.session.post(url, data=data)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 581, in post\n",
      "    return self.request('POST', url, data=data, json=json, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 533, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 646, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\adapters.py\", line 516, in send\n",
      "    raise ConnectionError(e, request=request)\n",
      "requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /update (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000205850AEC08>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다'))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception in user code:\n",
      "------------------------------------------------------------\n",
      "[2,   150] loss: 0.872\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 157, in _new_conn\n",
      "    (self._dns_host, self.port), self.timeout, **extra_kw\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\connection.py\", line 84, in create_connection\n",
      "    raise err\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\connection.py\", line 74, in create_connection\n",
      "    sock.connect(sa)\n",
      "ConnectionRefusedError: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 672, in urlopen\n",
      "    chunked=chunked,\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 387, in _make_request\n",
      "    conn.request(method, url, **httplib_request_kw)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1252, in request\n",
      "    self._send_request(method, url, body, headers, encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1298, in _send_request\n",
      "    self.endheaders(body, encode_chunked=encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1247, in endheaders\n",
      "    self._send_output(message_body, encode_chunked=encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1026, in _send_output\n",
      "    self.send(msg)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 966, in send\n",
      "    self.connect()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 184, in connect\n",
      "    conn = self._new_conn()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 169, in _new_conn\n",
      "    self, \"Failed to establish a new connection: %s\" % e\n",
      "urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000020580184788>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\adapters.py\", line 449, in send\n",
      "    timeout=timeout\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 720, in urlopen\n",
      "    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\retry.py\", line 436, in increment\n",
      "    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n",
      "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /update (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020580184788>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다'))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\visdom\\__init__.py\", line 711, in _send\n",
      "    data=json.dumps(msg),\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\visdom\\__init__.py\", line 677, in _handle_post\n",
      "    r = self.session.post(url, data=data)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 581, in post\n",
      "    return self.request('POST', url, data=data, json=json, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 533, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 646, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\adapters.py\", line 516, in send\n",
      "    raise ConnectionError(e, request=request)\n",
      "requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /update (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020580184788>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다'))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception in user code:\n",
      "------------------------------------------------------------\n",
      "[2,   180] loss: 0.894\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 157, in _new_conn\n",
      "    (self._dns_host, self.port), self.timeout, **extra_kw\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\connection.py\", line 84, in create_connection\n",
      "    raise err\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\connection.py\", line 74, in create_connection\n",
      "    sock.connect(sa)\n",
      "ConnectionRefusedError: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 672, in urlopen\n",
      "    chunked=chunked,\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 387, in _make_request\n",
      "    conn.request(method, url, **httplib_request_kw)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1252, in request\n",
      "    self._send_request(method, url, body, headers, encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1298, in _send_request\n",
      "    self.endheaders(body, encode_chunked=encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1247, in endheaders\n",
      "    self._send_output(message_body, encode_chunked=encode_chunked)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 1026, in _send_output\n",
      "    self.send(msg)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\http\\client.py\", line 966, in send\n",
      "    self.connect()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 184, in connect\n",
      "    conn = self._new_conn()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connection.py\", line 169, in _new_conn\n",
      "    self, \"Failed to establish a new connection: %s\" % e\n",
      "urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000020580184108>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\adapters.py\", line 449, in send\n",
      "    timeout=timeout\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 720, in urlopen\n",
      "    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\urllib3\\util\\retry.py\", line 436, in increment\n",
      "    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n",
      "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /update (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020580184108>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다'))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\visdom\\__init__.py\", line 711, in _send\n",
      "    data=json.dumps(msg),\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\visdom\\__init__.py\", line 677, in _handle_post\n",
      "    r = self.session.post(url, data=data)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 581, in post\n",
      "    return self.request('POST', url, data=data, json=json, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 533, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\sessions.py\", line 646, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\requests\\adapters.py\", line 516, in send\n",
      "    raise ConnectionError(e, request=request)\n",
      "requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /update (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020580184108>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다'))\n"
     ]
    }
   ],
   "source": [
    "print(len(trainloader))\n",
    "epochs = 2 #문제에서 요구한대로 epoch=2로 설정\n",
    "\n",
    "\n",
    "for epoch in range(epochs):  # loop over the dataset multiple times\n",
    "\n",
    "    running_loss = 0.0\n",
    "\n",
    "    for i, data in enumerate(trainloader, 0):\n",
    "        # get the inputs\n",
    "        inputs, labels = data\n",
    "        inputs = inputs.to(device)\n",
    "        labels = labels.to(device)\n",
    "\n",
    "        # zero the parameter gradients\n",
    "        optimizer.zero_grad()\n",
    "\n",
    "        # forward + backward + optimize\n",
    "        outputs = resnet34(inputs)\n",
    "        loss = criterion(outputs, labels)\n",
    "        loss.backward()\n",
    "        optimizer.step()\n",
    "\n",
    "        # print statistics\n",
    "        running_loss += loss.item()\n",
    "        if i % 30 == 29:    # print every 30 mini-batches\n",
    "            value_tracker(loss_plt, torch.Tensor([running_loss/30]), torch.Tensor([i + epoch*len(trainloader) ]))\n",
    "            print('[%d, %5d] loss: %.3f' %\n",
    "                  (epoch + 1, i + 1, running_loss / 30))\n",
    "            running_loss = 0.0\n",
    "\n",
    "\n",
    "print('Finished Training')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "오류를 어떻게 고쳐야할지 모르겠어서 그냥 제출합니다.ㅠㅠ 해결방법을 찾으면 다시 올리겠습니다."
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
